### ISSUE TITLE
Missing resource type for some uploaded datasets 

### ISSUE THREAD

**Issue by marthamareal** [GeoNode/geonode#8721] opened 2022-02-01 14:52 UTC
### Expected Behaviour
The `dataset` resource type is assigned.

### Actual Behaviour
resource type is missing.

### Steps to reproduce

1. Upload [this dataset](https://app.zenhub.com/files/23841932/f4c5d9e7-c27b-48c6-9d5d-9ad8eea3fa44/download)
2. Verify that it has been assigned the correct resource type

## Specifications

  - GeoNode version: master
  - Installation method (manual, GeoNode Docker, SPCGeoNode Docker):
  - Platform:
  - Additional details:

**Comment by giohappy** [comment] 2022-02-02 09:44
please @Stella-Nthenya test the fix.

**Comment by Stella-Nthenya** [comment] 2022-02-02 10:14
@marthamareal kindly confirm that the change has been deployed to https://master.demo.geonode.org/datasets/upload#
Note: I will test with the exact file without stripping off the xml files

**Comment by marthamareal** [comment] 2022-02-02 10:51
@giohappy the fix is not yet deployed on master yet.

**Comment by giohappy** [comment] 2022-02-02 11:46
@marthamareal @Stella-Nthenya the fix should already be deployed.

**Comment by Stella-Nthenya** [comment] 2022-02-02 13:09
Thanks @marthamareal . I can still replicate the issue.

**Comment by giohappy** [comment] 2022-02-02 13:17
I confirm, the issue is still present.

**Comment by marthamareal** [comment] 2022-02-02 13:25
I am unable to reproduce this locally, both uploading the shared zip and also uploading files with a single xml

**Comment by giohappy** [comment] 2022-02-02 14:56
@afabiani I see three problems here:

1 - the resource_type is set inside the save() method, which is executed only at the end of the ResourceManager.update(). If something wrong happens before reaching that point the resource is left in an inconsistent state
2 - ResourceManager.update() tries to read the xml file, but when the method is called the tmp folder with the files has been removed. I don't know if this is expected, but this is what I get locally (and I suppose it's the same problem happening for the demo isntance)
3 - This raises an exception which is [catched](https://github.com/GeoNode/geonode/blob/76d80ce898d86cc19830f07812b6c76b5b74bafa/geonode/resource/manager.py#L384-L387) to mark the resource dirty, but some code afterwords set the resource as correctly processed. Turns out that the resource looks good to the API and the client, but it isn't.

**Comment by afabiani** [comment] 2022-02-02 17:06
@giohappy [this commit](https://github.com/GeoNode/geonode/pull/8655/files/adb01d4ceb9f7f773c3ea7d340f51d3814a03f35..46b18eef8d05b433b817dbc3487d98c866e9b33a) fixes all those consistency issues you identified. This is part of another PR, the #8655

**Comment by afabiani** [comment] 2022-02-03 11:12
@giohappy I merged the PR, tests pass... please give it a try!

**Comment by giohappy** [comment] 2022-02-03 17:24
@afabiani @Stella-Nthenya looks good! Closing the issue.

**Closed by giohappy** 2022-02-03 17:24 UTC
Labels: blocker, master
