### ISSUE TITLE
Can't create group with non-ascii title

### ISSUE THREAD

**Issue by igor-chernikov** [GeoNode/geonode#2073] opened 2015-02-11 08:10 UTC
I tried to create group with russian characters in its title (e.g. "Группа"). I got the error:

    Internal Server Error: /groups/create/
    Traceback (most recent call last):
      File "D:\Python27\lib\site-packages\django\core\handlers\base.py", line 112, i
    n get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
      File "D:\Python27\lib\site-packages\django\contrib\auth\decorators.py", line 2
    2, in _wrapped_view
    return view_func(request, *args, **kwargs)
      File "D:\Projects\python\geonode\groups\views.py", line 29, in
     group_create
        group.slug]))
      File "D:\Python27\lib\site-packages\django\core\urlresolvers.py", line 536, in
     reverse
        return iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs))
      File "D:\Python27\lib\site-packages\django\core\urlresolvers.py", line 456, in _reverse_with_prefix
        (lookup_view_s, args, kwargs, len(patterns), patterns))
    NoReverseMatch: Reverse for 'group_detail' with arguments '(u'',)' and keyword arguments '{}' not
    found. 1 pattern(s) tried: ['groups/group/(?P<slug>[-\\w]+)/$']

The slug of saved group profile is empty string. It seems that django's SlugField doesn't support non-ascii chars.

**Comment by simod** [comment] 2015-02-11 09:16
Here's where the issue is https://github.com/GeoNode/geonode/blob/master/geonode/groups/forms.py#L37, django slugify only deals with acii characters. @ingenieroariel, we should add this dependency to solve this https://pypi.python.org/pypi/unicode-slugify. It doesn't seems be slugify package for ubuntu so we'll need to make one...

**Comment by simod** [comment] 2015-02-20 15:00
we can fix this one once https://github.com/GeoNode/geonode/pull/2081is merged because it brings in the unicode slugify

**Closed** 2015-02-23 10:08 UTC
Labels: bug
