### ISSUE TITLE
Assigning icons to TopicCategories

### ISSUE THREAD

**Issue by etj** [GeoNode/geonode#2495] opened 2016-06-09 09:01 UTC
As descripted in #2408, TopicCategories shoud have an icon associated.

Since there may be problems in handling the size in uploaded images, here's an implementation which uses the icons from [Font Awesome](http://fontawesome.io/). FontAwesome [is already used in GeoNode](https://github.com/GeoNode/geonode/tree/master/geonode/static/geonode/fonts) so there's no further data to add to the repo.

This is a first rendering of the TopicCats in the existing editor:
![topcat00](https://cloud.githubusercontent.com/assets/717359/15923870/98e067a2-2e2f-11e6-983b-7540507cf3ca.png)
and this is an example of how they are presented in the search page:

![topcat01](https://cloud.githubusercontent.com/assets/717359/15923918/d3fbd344-2e2f-11e6-8df1-bd6b43c786e0.png)

The admin can change the associated icon in the TopicCategory administration page by defining the FA class:

![topcat02](https://cloud.githubusercontent.com/assets/717359/15923962/1600e09a-2e30-11e6-8152-f3eb476b327b.png)

The default icon association has been copied from GeoNetwork, in order to keep coherent the graphic representation.

**Comment by capooti** [comment] 2016-06-09 18:10
I love it :)

**Comment by capooti** [comment] 2016-06-09 18:11
can you send a PR with this?

**Comment by etj** [comment] 2016-06-09 18:17
Already done, and already merged as far as I can see :)

**Comment by jj0hns0n** [comment] 2016-08-21 06:32
@artists974 has this been merged? can we close this?

**Comment by afabiani** [comment] 2016-08-21 11:17
Yep, closed.

Best Regards,
Alessio Fabiani.

==
GeoServer Professional Services from the experts!
Visit http://goo.gl/it488V for more information.
==

Ing. Alessio Fabiani
@alfa7691
Founder/Technical Lead

GeoSolutions S.A.S.
Via di Montramito 3/A
55054  Massarosa (LU)
Italy
phone: +39 0584 962313
fax:     +39 0584 1660272
mob:   +39 331 6233686

http://www.geo-solutions.it
http://twitter.com/geosolutions_it

-------------------------------------------------------

*AVVERTENZE AI SENSI DEL D.Lgs. 196/2003*

Le informazioni contenute in questo messaggio di posta elettronica e/o
nel/i file/s allegato/i sono da considerarsi strettamente riservate. Il
loro utilizzo è consentito esclusivamente al destinatario del messaggio,
per le finalità indicate nel messaggio stesso. Qualora riceviate questo
messaggio senza esserne il destinatario, Vi preghiamo cortesemente di
darcene notizia via e-mail e di procedere alla distruzione del messaggio
stesso, cancellandolo dal Vostro sistema. Conservare il messaggio stesso,
divulgarlo anche in parte, distribuirlo ad altri soggetti, copiarlo, od
utilizzarlo per finalità diverse, costituisce comportamento contrario ai
principi dettati dal D.Lgs. 196/2003.



The information in this message and/or attachments, is intended solely for
the attention and use of the named addressee(s) and may be confidential or
proprietary in nature or covered by the provisions of privacy act
(Legislative Decree June, 30 2003, no.196 - Italy's New Data Protection
Code).Any use not in accord with its purpose, any disclosure, reproduction,
copying, distribution, or either dissemination, either whole or partial, is
strictly forbidden except previous formal approval of the named
addressee(s). If you are not the intended recipient, please contact
immediately the sender by telephone, fax or e-mail and delete the
information in this message that has been received in error. The sender
does not give any warranty or accept liability as the content, accuracy or
completeness of sent messages and accepts no responsibility  for changes
made after they were sent or for other risks which arise as a result of
e-mail transmission, viruses, etc.

---------------------------------------------------------------------

**Closed** 2016-08-21 11:17 UTC
Labels: metadata, ui/ux
