### ISSUE TITLE
Website: multiple disturbing 404 on very prominent places

### ISSUE THREAD

**Issue by supersexy** [GeoNode/geonode#4609] opened 2019-07-06 11:45 UTC
The frontpage of geonode.org contains many 404s, but also the most important action buttons on the User / Admin / Developer sections are 404.

The website should be monitored for such errors. From the repo activity it looks like this project is not dead, but users that visit the website will think exactly that. 

http://docs.geonode.org/en/latest/tutorials/install_and_admin/index.html
http://docs.geonode.org/en/latest/tutorials/install_and_admin/quick_install.html

http://docs.geonode.org/en/latest/tutorials/users/
http://docs.geonode.org/en/latest/tutorials/devel/
http://docs.geonode.org/en/latest/tutorials/admin/

**Comment by t-book** [comment] 2019-07-06 19:36
@supersexy Welcome onboard and thanks for your feedback.
I`ve just updated these two links:
http://docs.geonode.org/en/latest/tutorials/install_and_admin/index.html
http://docs.geonode.org/en/latest/tutorials/install_and_admin/quick_install.html

but could not spot the others on the geonode.org front page. However, the issue is known and on our list. The community just updated the docs (still in progress). The website hopefully comes next (some more parts like the quick install or FAQs are outdated as well –  next to the Github [wiki](https://github.com/GeoNode/geonode/wiki)) ... Helping hands always very welcome. 

I would suggest to either close this issue and create a new one which collects all things which need to be updated or to rename this issue (broader) and continue here.

**Comment by t-book** [comment] 2019-07-07 14:58
Fixed the remaining mentioned links. Closing here in favor for https://github.com/GeoNode/geonode.github.com/issues/79

**Closed by t-book** 2019-07-07 14:58 UTC
