### ISSUE TITLE
Duplicated links in Raster

### ISSUE THREAD

**Issue by ingenieroariel** [GeoNode/geonode#1567] opened 2014-07-03 13:29 UTC
Replicated in the 2.0.x branch and affects the 2.0 final7 artifact.

**Comment by jj0hns0n** [comment] 2015-01-13 17:07
Can we close this one?

**Comment by jj0hns0n** [comment] 2015-02-03 11:25
As far as I can tell this has been fixed. Closing.

**Closed by jj0hns0n** 2015-02-03 11:25 UTC
Labels: bug, verify

**Comment by capooti** [comment] 2015-02-03 11:58
could be a dupe of #1090  that should have been fixed
