### ISSUE TITLE
Updatelayers with --skip-unadvertised fails for cascaded WMS layers.

### ISSUE THREAD

**Issue by garnertb** [GeoNode/geonode#1889] opened 2014-12-11 16:06 UTC
`updatelayers` throws an AttributeError when the `--skip-unadvertised` switch is used on a Cascaded WMS Layer.  This does not require any changes to GeoNode, however once https://github.com/boundlessgeo/gsconfig/pull/90 is merged, we need to bump the gsconfig dependency.

**Comment by jj0hns0n** [comment] 2015-02-03 09:51
@garnertb any update on this from

**Comment by garnertb** [comment] 2015-02-03 11:22
Hold.  Still pending boundlessgeo/gsconfig#90.

**Comment by jj0hns0n** [comment] 2015-02-04 14:18
If I'm not mistaken, @ingenieroariel created a new gsconfig package after @ischneider pulled this PR. @garnertb can you test and close if possible?

**Comment by simod** [comment] 2015-02-20 14:44
Any updates on this? Can we close it?

**Comment by capooti** [comment] 2015-03-12 13:58
I wanted to test this but I am experiencing a different behavior of updatelayers from the past, so please forgive me If I now go off topic.
I created a cascaded layer from another GeoServer instance, and I can correctly access the layer in the GeoServer preview.
When running the updatelayers command now the layer is skipped (with 2.0 it would have been instead registered in GeoNode). Should I file another ticket with this, or this is the intended behavior?

**Closed** 2015-04-08 12:54 UTC
Labels: bug, management-commands, remote-services
