### ISSUE TITLE
After running "docker-compose up" geoserver, geonode, postgis and postgres are unavailable

### ISSUE THREAD

**Issue by markich** [GeoNode/geonode#3676] opened 2018-03-21 22:07 UTC
We are trying to have a fully functional Geonode instance and after successfully installing **Docker**  on a _**Ubuntu 16.04 LTS (Xenial)**_ we ran ```docker-compose up --build``` with the following updated/modified *"docker-compose.yml"* file:

```
version: '2.1'
services:

  db:
    image: geonode/postgis:9.6
    restart: unless-stopped
    container_name: db4${COMPOSE_PROJECT_NAME}
    stdin_open: true
    # tty: true
    labels:
        org.geonode.component: db
        org.geonode.instance.name: geonode
    volumes:
      - dbdata:/var/lib/postgresql/data
      - dbbackups:/pg_backups
    env_file:
      - ./scripts/docker/env/production/db.env

  elasticsearch:
    image: elasticsearch
    restart: unless-stopped
    container_name: elasticsearch4${COMPOSE_PROJECT_NAME}
    stdin_open: true
    # tty: true
    labels:
        org.geonode.component: elasticsearch
        org.geonode.instance.name: geonode

  rabbitmq:
    image: rabbitmq
    restart: unless-stopped
    container_name: rabbitmq4${COMPOSE_PROJECT_NAME}
    stdin_open: true
    # tty: true
    labels:
        org.geonode.component: rabbitmq
        org.geonode.instance.name: geonode

  django:
    restart: unless-stopped
    image: geonode/geonode:latest
    container_name: django4${COMPOSE_PROJECT_NAME}
    stdin_open: true
    # tty: true
    labels:
        org.geonode.component: django
        org.geonode.instance.name: geonode
    depends_on:
      - db
      - elasticsearch
      - rabbitmq
    command: django-admin.py runserver 0.0.0.0:8000 --settings=geonode.settings
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    env_file:
      - ./scripts/docker/env/production/django.env

  celery:
    restart: unless-stopped
    image: geonode/geonode:latest
    container_name: celery4${COMPOSE_PROJECT_NAME}
    stdin_open: true
    # tty: true
    labels:
        org.geonode.component: celery
        org.geonode.instance.name: geonode
    depends_on:
      - db
      - elasticsearch
      - rabbitmq
    command: celery worker --app=geonode.celery_app:app -B -l INFO
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    env_file:
      - ./scripts/docker/env/production/celery.env

  consumers:
    image: geonode/geonode:latest
    restart: unless-stopped
    container_name: consumers4${COMPOSE_PROJECT_NAME}
    stdin_open: true
    # tty: true
    labels:
        org.geonode.component: consumers
        org.geonode.instance.name: geonode
    depends_on:
      - rabbitmq
      - db
      - elasticsearch
    command: python manage.py runmessaging
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    env_file:
      - ./scripts/docker/env/production/django.env

  geoserver:
    image: geonode/geoserver:2.12.x
    restart: unless-stopped
    container_name: geoserver4${COMPOSE_PROJECT_NAME}
    stdin_open: true
    # tty: true
    labels:
        org.geonode.component: geoserver
        org.geonode.instance.name: geonode
    depends_on:
      - db
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - geoserver-data-dir:/geoserver_data/data
    env_file:
      - ./scripts/docker/env/production/geoserver.env

  geonode:
    image: geonode/nginx:geoserver
    restart: unless-stopped
    container_name: nginx4${COMPOSE_PROJECT_NAME}
    stdin_open: true
    # tty: true
    labels:
        org.geonode.component: nginx
        org.geonode.instance.name: geonode
    depends_on:
      - django
      - geoserver
    ports:
      - "8888:80"
    expose:
      - "80"

  data-dir-conf:
    image: geonode/geoserver_data:2.12.x
    restart: on-failure
    container_name: gsconf4${COMPOSE_PROJECT_NAME}
    labels:
        org.geonode.component: conf
        org.geonode.instance.name: geonode
    command: /bin/true
    volumes:
      - geoserver-data-dir:/geoserver_data/data

volumes:

  geoserver-data-dir:
    external: false
    name: ${COMPOSE_PROJECT_NAME}-gsdatadir
  dbdata:
    external: false
    name: ${COMPOSE_PROJECT_NAME}-dbdata
  dbbackups:
    external: false
    name: ${COMPOSE_PROJECT_NAME}-dbbackups
```
After a couple of test runs we have not been able to connect to **postgis**, neither to the **geoserver** admin page on `<server-ip-address>:8888/geoserver/web` nor the default **geonode** main page.

1st Run
=============================================
```
docker ps
docker exec -it db4geonode bash
psql -h <server-ip-address> -p 5432 -U postgres
```

2nd Run
=============================================
```
cd ./home/geonode/
docker-compose down
docker-compose up
docker ps
docker exec -it db4geonode bash
psql -h <server-ip-address> -p 5432 -U postgres
```

3rd Run
=============================================
```
cd ./home/geonode/
docker-compose down
docker-compose up
docker ps
docker exec -it db4geonode bash
su postgres
psql
CREATE DATABASE first_test_db;
psql -h <server-ip-address> -p 5432 -U postgres
\l
```

**Comment by markich** [comment] 2018-03-21 22:58
@francbartoli We would appreciate all the possible help that you might be able to provide us with.
I've been reading all existent issues and I have not encountered any similar issue. Do you know where we can request more information on this matter?

**Comment by francbartoli** [comment] 2018-03-22 10:03
@markich I see you have changed the port. What's your goal?

**Comment by Pablovsky83** [comment] 2018-03-22 17:50
We are trying to make a spatial data infrastructure, based on geonode working on a server we have rented. The problem is that, although we have been able to correctly install the docker modules, from the official container, we can't operate the main page of our project (the basic one of geonode), geoserver or postgis, to enter remotely from the browser, pgadmin or qgis. Our goal is to solve that for the moment.

**Comment by francbartoli** [comment] 2018-03-22 18:48
@pablovsky83 assuming you have a public ip/fqdn where you want to navigate geonode then you have just to configure that in the variable:

GEONODE_LB_HOST_IP=<fqdn/ip>

Eventually the port:

GEONODE_LB_PORT=<port>

In each of the .env files. You don’t need anything else.

**Comment by markich** [comment] 2018-03-23 00:10
@francbartoli Thanks for your responses! We have the following files in **/home/geonode/scripts/docker/env/production**:

First, we have _**celery.env**_:
```
GEONODE_INSTANCE_NAME=geonode
GEONODE_LB_HOST_IP=<server-ip-address>
GEONODE_LB_PORT=8000
DATABASE_URL=postgres://postgres:postgres@db:5432/postgres
DEFAULT_BACKEND_DATASTORE=datastore
GEONODE_DATABASE=geonode
GEONODE_DATABASE_PASSWORD=geonode
GEONODE_GEODATABASE=geonode_data
GEONODE_GEODATABASE_PASSWORD=geonode_data
BROKER_URL=amqp://guest:guest@rabbitmq:5672/
DJANGO_SETTINGS_MODULE=geonode.settings
ALLOWED_HOSTS=['django',]
DOCKER_ENV=production
CELERY_CMD=celery worker --app=geonode.celery:app --broker=amqp://guest:guest@rabbitmq:5672/ -B -l INFO
IS_CELERY=true
C_FORCE_ROOT=1
GEOSERVER_PUBLIC_LOCATION=<server-ip-address>:8888/geoserver/web/
GEOSERVER_LOCATION=<server-ip-address>:8888/geoserver/web/
SITEURL=<server-ip-address>
```

Then, we have _**db.env**_:
```
GEONODE_DATABASE=geonode
GEONODE_DATABASE_PASSWORD=geonode
GEONODE_GEODATABASE=geonode_data
GEONODE_GEODATABASE_PASSWORD=geonode_data
```

In addition, we have _**django.env**_:
```
GEONODE_INSTANCE_NAME=geonode
GEONODE_LB_HOST_IP=<server-ip-address>
GEONODE_LB_PORT=8000
DATABASE_URL=postgres://postgres:postgres@db:5432/postgres
DEFAULT_BACKEND_DATASTORE=datastore
GEONODE_DATABASE=geonode
GEONODE_DATABASE_PASSWORD=geonode
GEONODE_GEODATABASE=geonode_data
GEONODE_GEODATABASE_PASSWORD=geonode_data
BROKER_URL=amqp://guest:guest@rabbitmq:5672/
DJANGO_SETTINGS_MODULE=geonode.settings
ALLOWED_HOSTS=['django',]
DOCKER_ENV=production
UWSGI_CMD=uwsgi --ini /usr/src/app/uwsgi.ini
IS_CELERY=false
C_FORCE_ROOT=1
GEOSERVER_PUBLIC_LOCATION=http://geonode/geoserver/
GEOSERVER_LOCATION=http://geonode/geoserver/
```

Finally, we have _**geoserver.env**_:
```
DOCKERHOST
GEONODE_LB_HOST_IP=<server-ip-address>
GEONODE_LB_PORT=8000
PUBLIC_PORT=80
DOCKER_HOST_IP
```

Furthermore, we have another folder on a previoius level called **development** which has the following files:

_**db.env**_:
```
GEONODE_DATABASE=geonode
GEONODE_DATABASE_PASSWORD=geonode
GEONODE_GEODATABASE=geonode_data
GEONODE_GEODATABASE_PASSWORD=geonode_data
```

_**django.env**_:
```
GEONODE_INSTANCE_NAME=geonode
BROKER_URL=amqp://guest:guest@rabbitmq:5672/
DJANGO_SETTINGS_MODULE=geonode.settings
GEOSERVER_INTERNAL_URL=http://geoservices:8080/geoserver/
ALLOWED_HOSTS=['django',]
DOCKER_ENV=development
DOCKER_HOST
PUBLIC_PORT=8000
DOCKER_HOST_IP
DEBUG=True
C_FORCE_ROOT=1
```

_**geoserver.env**_:
```
DOCKER_HOST
PUBLIC_PORT=8000
```

Our questions are:

1. Do we have to just modify variables **GEONODE_LB_HOST_IP** and **GEONODE_LB_PORT** by adding our server IP address and whatever port we choose in **celery.env**, **django.env** and **geoserver.env**? If not, then which port should we assign?
2. Do we have to modify any other configuration or settings file (eg. _**/home/geonode/geonode/settings.py**_ or _**/home/geonode/geonode/local_settings.py**_)?
3. We have a firewall implemented with _iptables_: Do we have to modify any configuration of the available rules listed by doing _iptables --list_?
4. Should we take into account any other extra step on our setup?

@Pablovsky83 Am I missing something else here?

**Comment by Pablovsky83** [comment] 2018-03-23 00:14
I guess that´s all by now @markich !  By the way, in the celery.env the part filled with 

GEOSERVER_PUBLIC_LOCATION=<server-ip-address>:8888/geoserver/web/
GEOSERVER_LOCATION=<server-ip-address>:8888/geoserver/web/

is now like the original 

GEOSERVER_PUBLIC_LOCATION=http://geonode/geoserver/
GEOSERVER_LOCATION=http://geonode/geoserver/

anyway, is not working with the changes i made.

**Comment by francbartoli** [comment] 2018-03-23 08:08
@markich @Pablovsky83 I'll give you an example. If you want to publish geonode on the domain example.geonode.org on port 80 then you must only configure after a github cloning:

GEONODE_LB_HOST_IP=example.geonode.org
GEONODE_LB_PORT=80

in geoserver.env, celery.env, django.env.
If you have a firewall then it's up to your team to make sure that the resolved ip address for that domain and the port have a route to the docker0 ip address of your server.
So if the issue is with the network/firewall configuration we should kindly move the discussion to the geonode mailing list unless the problem is with the code then in this case I need to figure out how to replicate the error.

**Comment by Pablovsky83** [comment] 2018-03-23 22:19
We made those changes on the .env files, we disabled the the firewall but it keeps sending us to the apache2 ubuntu default page. We tryed to connect by Pgadmin to the database, but it rejected us (with the firewall disable too).

This is our docker ps:

docker ps
```
CONTAINER ID        IMAGE                      COMMAND                  CREATED             STATUS              PORTS                                NAMES
186dc28b244b        geonode/nginx:geoserver    "nginx -g 'daemon of…"   39 minutes ago      Up 39 minutes       0.0.0.0:8888->80/tcp                 nginx4geonode
8860c7ac99ab        geonode/geonode:latest     "/usr/src/app/entryp…"   39 minutes ago      Up 39 minutes       8000/tcp                             celery4geonode
27680b9757e3        geonode/geonode:latest     "/usr/src/app/entryp…"   39 minutes ago      Up 39 minutes       8000/tcp                             django4geonode
a282f2cb3896        geonode/geonode:latest     "/usr/src/app/entryp…"   39 minutes ago      Up 39 minutes       8000/tcp                             consumers4geonode
6eacf6568689        geonode/geoserver:2.12.x   "/usr/local/tomcat/t…"   39 minutes ago      Up 39 minutes       8080/tcp                             geoserver4geonode
8e7fbf748088        geonode/postgis:9.6        "docker-entrypoint.s…"   39 minutes ago      Up 39 minutes       5432/tcp                             db4geonode
94bad42ba148        rabbitmq                   "docker-entrypoint.s…"   39 minutes ago      Up 39 minutes       4369/tcp, 5671-5672/tcp, 25672/tcp   rabbitmq4geonode
351485c47fef        elasticsearch              "/docker-entrypoint.…"   39 minutes ago      Up 39 minutes       9200/tcp, 9300/tcp                   elasticsearch4geonode
``` 

All containers are running ok

Our .env files are this:

Celery.env

```
GEONODE_INSTANCE_NAME=geonode
GEONODE_LB_HOST_IP=190.111.252.249
GEONODE_LB_PORT=80
DATABASE_URL=postgres://postgres:postgres@db:5432/postgres
DEFAULT_BACKEND_DATASTORE=datastore
GEONODE_DATABASE=geonode
GEONODE_DATABASE_PASSWORD=geonode
GEONODE_GEODATABASE=geonode_data
GEONODE_GEODATABASE_PASSWORD=geonode_data
BROKER_URL=amqp://guest:guest@rabbitmq:5672/
DJANGO_SETTINGS_MODULE=geonode.settings
ALLOWED_HOSTS=['django',]
DOCKER_ENV=production
CELERY_CMD=celery worker --app=geonode.celery:app --broker=amqp://guest:guest@rabbitmq:5672/ -B -l INFO
IS_CELERY=true
C_FORCE_ROOT=1
GEOSERVER_PUBLIC_LOCATION=http://geonode/geoserver/
GEOSERVER_LOCATION=http://geonode/geoserver/
SITEURL=http://geonode/
``` 

django.env

```
GEONODE_INSTANCE_NAME=geonode
GEONODE_LB_HOST_IP=190.111.252.249
GEONODE_LB_PORT=80
DATABASE_URL=postgres://postgres:postgres@db:5432/postgres
DEFAULT_BACKEND_DATASTORE=datastore
GEONODE_DATABASE=geonode
GEONODE_DATABASE_PASSWORD=geonode
GEONODE_GEODATABASE=geonode_data
GEONODE_GEODATABASE_PASSWORD=geonode_data
BROKER_URL=amqp://guest:guest@rabbitmq:5672/
DJANGO_SETTINGS_MODULE=geonode.settings
ALLOWED_HOSTS=['django',]
DOCKER_ENV=production
UWSGI_CMD=uwsgi --ini /usr/src/app/uwsgi.ini
IS_CELERY=false
C_FORCE_ROOT=1
GEOSERVER_PUBLIC_LOCATION=http://geonode/geoserver/
GEOSERVER_LOCATION=http://geonode/geoserver/
SITEURL=http://geonode/

``` 

And geoserver.env

```
DOCKERHOST
GEONODE_LB_HOST_IP=190.111.252.249
GEONODE_LB_PORT=80
PUBLIC_PORT=80
DOCKER_HOST_IP=172.17.0.1
``` 
Don´t know what we are doing wrong. Firewall is not the problem it seems cause we disable it...

**Comment by bssher** [comment] 2018-03-24 19:19
Any update on this? I am having the same issue.

**Comment by Pablovsky83** [comment] 2018-03-24 19:40
not yet @bssher

**Comment by francbartoli** [comment] 2018-03-30 08:55
@Pablovsky83 it isn't definitively a bug, not exposing the internal ports (PostGIS, GeoServer, etc) on the public network is something we want to achieve. I'm going to close this

**Closed by francbartoli** 2018-03-30 08:55 UTC

**Comment by bssher** [comment] 2018-05-05 19:44
any update?

**Comment by s-chand** [comment] 2018-07-06 09:18
@Pablovsky83 @markich Just a couple of questions:

1. Are you running the ubuntu instance within a VM?
2. Why aren't you disabling the ubuntu's default apache server?
3. What version of geonode were you trying to run ?

**Comment by s-chand** [comment] 2018-07-06 09:21
Also, I see that you have successfully gotten it to work, However, it would be useful to others if you shared what eventually worked for you.
