### ISSUE TITLE
How does the mapping list display? (file  base_resourcebase_snippet.html )

### ISSUE THREAD

**Issue by leslie971** [GeoNode/geonode#3671] opened 2018-03-15 17:40 UTC
G ood Morning

I would like to know how are loaded and selected the data that appear in the file geonode / base / templates / base_resourcebase_snippet.html
What is the file that selects the data?
I would like to use the display of the base_resourcebase_snippet.html file but with slightly different data

Thanks.

**Comment by afabiani** [comment] 2018-03-16 08:50
Hi,
that file is populated by resources filtered through Tastipye from
resourcebase_api.py

Be careful, that file makes use of angularJS and therefore currently it is
slightly different from a standard Django template.

Regards,

Alessio Fabiani

==
GeoServer Professional Services from the experts! Visit http://goo.gl/it488V
for more information.
==

Ing. Alessio Fabiani

@alfa7691
Founder/Technical Lead


GeoSolutions S.A.S.
Via di Montramito 3/A
55054  Massarosa (LU)
Italy
phone: +39 0584 962313
fax:     +39 0584 1660272
mob:   +39 331 6233686

http://www.geo-solutions.it
http://twitter.com/geosolutions_it

-------------------------------------------------------

AVVERTENZE AI SENSI DEL D.Lgs. 196/2003

Le informazioni contenute in questo messaggio di posta elettronica e/o
nel/i file/s allegato/i sono da considerarsi strettamente riservate. Il
loro utilizzo è consentito esclusivamente al destinatario del messaggio,
per le finalità indicate nel messaggio stesso. Qualora riceviate questo
messaggio senza esserne il destinatario, Vi preghiamo cortesemente di
darcene notizia via e-mail e di procedere alla distruzione del messaggio
stesso, cancellandolo dal Vostro sistema. Conservare il messaggio stesso,
divulgarlo anche in parte, distribuirlo ad altri soggetti, copiarlo, od
utilizzarlo per finalità diverse, costituisce comportamento contrario ai
principi dettati dal D.Lgs. 196/2003.

The information in this message and/or attachments, is intended solely for
the attention and use of the named addressee(s) and may be confidential or
proprietary in nature or covered by the provisions of privacy act
(Legislative Decree June, 30 2003, no.196 - Italy's New Data Protection
Code).Any use not in accord with its purpose, any disclosure, reproduction,
copying, distribution, or either dissemination, either whole or partial, is
strictly forbidden except previous formal approval of the named
addressee(s). If you are not the intended recipient, please contact
immediately the sender by telephone, fax or e-mail and delete the
information in this message that has been received in error. The sender
does not give any warranty or accept liability as the content, accuracy or
completeness of sent messages and accepts no responsibility  for changes
made after they were sent or for other risks which arise as a result of
e-mail transmission, viruses, etc.

2018-03-15 18:40 GMT+01:00 leslie971 <notifications@github.com>:

**Comment by leslie971** [comment] 2018-03-19 14:56
thanks

**Comment by leslie971** [comment] 2018-03-20 15:58
I would like to recuperate the data sent by url http://127.0.0.1:8000/api/entry/ and be able to display them in the geonode home page.
  url call with JQUERY AJAX?
my api file is like https://django-tastypie.readthedocs.io/en/latest/tutorial.html
 
I tried something like this:

<script>
$(document).ready (function () {
 $("div1").load( URL);
});
</script>

<div id="div1"> </div>

how to get each object  and display each ?  
with ng-repeat ?

thanks

**Comment by simod** [comment] 2018-03-21 08:32
Hi, yes we use angular. You can tweak the featured section here https://github.com/GeoNode/geonode/blob/master/geonode/templates/index.html#L316.

I'm closing this as is not an issue, please use the mailing list to ask for support.

Best

**Closed by simod** 2018-03-21 08:32 UTC
