### ISSUE TITLE
Geonode not displaying encoding UTF-8

### ISSUE THREAD

**Issue by SaudiGIS** [GeoNode/geonode#4828] opened 2019-09-05 20:24 UTC
I'm trying to upload shapefile datasource to Geonode 2.8. It successfully upload, but I found character encoding problems. Shapefile does contain characters UTF-8 when the client display encoding are not UTF-8.

install docker-geonode

Example: 
https://imgur.com/vjf12jV

thank you very much for your help

## Specifications

  - GeoNode version: 2.8
  - Installation method: GeoNode Docker
  - Platform: Ubuntu 16.04.6 (LTS) x64
  - Additional details: DigitalOcean Server

**Comment by SaudiGIS** [comment] 2019-09-05 20:37
Example:
https://imgur.com/vjf12jV

**Comment by t-book** [comment] 2019-09-11 06:05
@SaudiGIS Any chance to 
- Update the viewer to mapstore2
- Provide us your sample data

**Comment by afabiani** [comment] 2019-09-11 07:32
Dear all,
this is a known issue. The situation currently is the following one:
1. The "geonode.rest" uploader method supports encoding. You will need to select the correct one from the upload page. But it is a bit limited. It supports fewer formats and does not support temporal series.
2. The "geonode.importer" uploader method does not propagate the encoding to GeoServer, currently. This issue has been fixed on GeoServer recently, so it will be available on GeoNode with the next GeoServer upgrade.

**Comment by gannebamm** [comment] 2019-11-04 10:10
> The "geonode.importer" uploader method does not propagate the encoding to GeoServer, currently. **This issue has been fixed on GeoServer recently, so it will be available on GeoNode with the next GeoServer upgrade.**

Is this still an issue?

**Comment by afabiani** [comment] 2019-11-04 10:12
yeps, we need a new GeoServer version to get this fixed.

**Comment by afabiani** [comment] 2019-11-07 09:23
This is a duplicate of https://github.com/GeoNode/geonode/issues/4635

Moreover, the fix will be backported to 2.10 version only. So, please, consider upgrading your GeoNode version ASAP.

**Closed by afabiani** 2019-11-07 09:23 UTC
Labels: minor
