### ISSUE TITLE
Error 404 NOT FOUND

### ISSUE THREAD

**Issue by juliermegeotube** [GeoNode/geonode#3691] opened 2018-03-28 13:51 UTC
Hi all,

First of all, my apologies if this question has been discussed before. I am running Geonode 2.6.3 with Geoserver 2.12.2 and anytime I open a Map I get the following Error:

"The server returned an error: 404 NOT FOUND"
Details:
HTTP Status 404 -
type Status report
message
description The request resource is not available.

Apache Tomcat/7.0.76

I have configured the local_settings.py Proxy_Allowed_Hosts, but still getting this error message.

has anyone faced the same issue? If so, how did you solve it?

Thank you for your time in advance

Best Regards

**Comment by simod** [comment] 2018-03-29 12:40
Hi, we would need more info about the error, in particular to which request the error is referring to. You can find that in the browser console.

Could you please move this conversation to the mailing lists? I'm going to close this one as is not a bug at the moment.

**Closed by simod** 2018-03-29 12:40 UTC
