### ISSUE TITLE
GeoNode Backup & Restore can't backup Cascaded WMS Layer (or maybe: Geoserver can't backup)

### ISSUE THREAD

**Issue by jannefleischer** [GeoNode/geonode#6501] opened 2020-10-05 13:38 UTC
## Expected Behavior
Backup the whole GeoNode incl. all layers from Geoserver into an archive.

## Actual Behavior
Backup failes when one of the Geonode-Layers is actually a Cascaded WMS Layer

## Steps to Reproduce the Problem

1. Create a layer in GeoServer as a [Cascaded WMS](https://docs.geoserver.org/latest/en/user/data/cascaded/wms.html)
2. Add it via "python manager.py importlayers" to geonode.
3. write a backup via python manage.py backup ...

It failes at Step 6/11 and basically reports "java.lang.IllegalArgumentException: Could not find a security wrapper for class class org.geoserver.catalog.impl.WMSStoreInfoImpl, cannot secure the object"
I created a [gist](https://gist.github.com/jannefleischer/3e2f402fb706434e66f11d045ee1f86a)

I am guessing: This should be fixed in Geoserver (or maybe is in a current version?), but in case I am wrong, I like to leave this issue here.

## Specifications

  - GeoNode version: 2.10.4 (with GeoServer 2.14)
  - Installation method (manual, GeoNode Docker, SPCGeoNode Docker): Manual install
  - Platform: Ubuntu-18-04
  - Additional details: grown version from 2.8 to 2.10.0 to 2.10.4 (at last step stayed at GeoServer 2.14 instead of moving to 2.16)

**Comment by afabiani** [comment] 2020-10-06 07:30
@jannefleischer any chance to try a newer version of GeoServer? Or maybe try an updated 2.14 or 1.5 WAR from here

https://build.geo-solutions.it/geonode/geoserver/latest/

I remember that BR extension had some issues which should have been fixed on the latest versions.

**Comment by jannefleischer** [comment] 2020-10-06 09:26
I am in the middle of a server move, so I just deleted that one Cascaded WMS Layer and everything went good.

**Comment by t-book** [comment] 2020-10-23 21:09
This looks like the issue is solved. please reopen if needed.

**Closed by t-book** 2020-10-23 21:09 UTC
