### ISSUE TITLE
Uploading UI Permissions Widget / Lock

### ISSUE THREAD

**Issue by state-hiu** [GeoNode/geonode#2125] opened 2015-04-14 17:32 UTC
When uploading a new shapefile on the `/layers/upload` page, the permissions widget and other UI buttons should lock, disable, or show some UI to indicate that after uploading a file, the permissions widget has no effect.  Same should go for documents upload page.

**Comment by simod** [comment] 2015-04-15 06:11
I think we can close this as dupe of https://github.com/GeoNode/geonode/issues/1791

**Closed by simod** 2015-04-15 06:11 UTC
