### ISSUE TITLE
Unable to clone a dataset uploaded along with an XML metadata

### ISSUE THREAD

**Issue by afabiani** [GeoNode/geonode#9196] opened 2022-04-20 16:42 UTC
## Expected Behavior
The dataset is cloned successfully.

## Actual Behavior
We get an exception from the `scan_file` utility method

```
invalid JSON response: b'{"import":{"id":114,"href":"http://localhost:8080/geoserver/rest/imports/114","state":"COMPLETE","archive":false,"tasks": .......'
Expecting value: line 1 column 2719 (char 2718)
Traceback (most recent call last):
  File "/opt/geonode/geonode/resource/manager.py", line 476, in copy
    _resource = self._concrete_resource_manager.copy(instance, uuid=_resource.uuid, defaults=to_update)
  File "/opt/geonode/geonode/geoserver/manager.py", line 168, in copy
    _src_importer_session = _src_upload_session.get_session.import_session.reload()
  File "/home/marthamareal/.virtualenvs/geonode/lib/python3.8/site-packages/gsimporter/api.py", line 93, in reload
    parsed = parse_response(resp, parent=self._parent or self)
  File "/home/marthamareal/.virtualenvs/geonode/lib/python3.8/site-packages/gsimporter/api.py", line 52, in parse_response
    raise ex
  File "/home/marthamareal/.virtualenvs/geonode/lib/python3.8/site-packages/gsimporter/api.py", line 49, in parse_response
    resp = json.loads(response.decode('ISO-8859-1'))
  File "/usr/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 2719 (char 2718)
```

## Steps to Reproduce the Problem

  1. Upload this file [Africa water body.zip](https://github.com/GeoNode/geonode/files/8523496/Africa.water.body.zip)
  2. Try to clone the Dataset
  3. Verify from the GeoNode logs that there's an exception and the cloned resource won't be available

## Specifications

  - GeoNode version: 4.x
  - Installation method (manual, GeoNode Docker, SPCGeoNode Docker):
  - Platform:
  - Additional details:

**Comment by mattiagiupponi** [comment] 2022-05-11 14:59
@afabiani I tried several times (both sync and async) but I'm not able to reproduce the issue.

The only issue that I'm able to reproduce (that is fixed by this PR: https://github.com/GeoNode/geonode/pull/9322) is related to another problem always into the scan_file method:

```python
One or more XML files were provided, but no matching files were found for them.
Traceback (most recent call last):
  File "/opt/core/geonode/geonode/geoserver/manager.py", line 215, in import_dataset
    _gs_import_session_info = self._execute_resource_import(
  File "/opt/core/geonode/geonode/geoserver/manager.py", line 291, in _execute_resource_import
    spatial_files_type = get_spatial_files_dataset_type(ALLOWED_EXTENSIONS, files)
  File "/opt/core/geonode/geonode/geoserver/helpers.py", line 2249, in get_spatial_files_dataset_type
    spatial_files = scan_file(
  File "/opt/core/geonode/geonode/upload/files.py", line 314, in scan_file
    raise Exception(_("One or more XML files was provided, but no matching files were found for them."))
Exception: One or more XML files were provided, but no matching files were found for them.
```
In a nutshell, when the storage_manager copies the files related to a resource, those files were saved into the same folder as the original ones. This makes the scan_file fail because more than one XML file was found.

Can you try again to upload the resource and see if the issue is still available? (this is because it looks like a bad communication with GeoServer)

**Closed** 2022-05-11 15:24 UTC
Labels: minor, master, 4.0.x
