### ISSUE TITLE
Layer is not updated when using API (Geonode 4.1 Stable branch)

### ISSUE THREAD

**Issue by daarias331** [GeoNode/geonode#11532] opened 2023-09-26 06:46 UTC
## Expected Behavior
When using API call to upload layer and set **overwrite_existing_layer** to True, I should see the new layer reflected.

## Actual Behavior
I see the old data. The only thing that changes is the **last catalog modification,** which reflects the date time when I tried to update (overwrite) the layer.
![image](https://github.com/GeoNode/geonode/assets/69835411/71eb2a06-4775-4793-ab54-81b3f5ac8a43)

## Steps to Reproduce the Problem

  1. Decompress zip1
  2. Upload using API
 
![image](https://github.com/GeoNode/geonode/assets/69835411/b04bb9f4-2893-4f2d-998e-5fa7ec07a744)

  3. See how the layer looks in Geonode
  5. Decompress zip 2 (new version of the previous layer, with the exact same name)
  6. Upload contents of zip2 using the API
  7. See how layers look in Geonode. You will see that only **last catalog modification**  in the information panel of the layer is modified. However, the layer displayed is the same as the old layer
  
## Specifications

Tested on 2 environments. 

First one is geonode's test [https://stable.demo.geonode.org/](https://stable.demo.geonode.org/)

Second was my VM from Melbourne research cloud
  - GeoNode version: 4.1.x stable branch
  - Installation type (vanilla, geonode-project):  geonode-project
  - Installation method (manual, docker): docker
  - Platform: 22.04.2 LTS (Jammy Jellyfish)
  - Additional details: Results were the same for both geonode's demo instance and my own VM. I found a
[zip2.zip](https://github.com/GeoNode/geonode/files/12723710/zip2.zip)
[zip1.zip](https://github.com/GeoNode/geonode/files/12723711/zip1.zip)
 related [issue here](https://github.com/GeoNode/geonode/issues/6447) , although it was for Geonode 3.1 and it is done via web UI instead of API

**Comment by giohappy** [comment] 2023-09-26 09:09
Thanks @daarias331. An investigation has been scheduled to reproduce the issue.

**Comment by mattiagiupponi** [comment] 2023-09-26 13:56
@giohappy @daarias331 
Actually is an issue and is true, the importer wrongly extract the name of the instance to be replaced. I'm going to fix it

**Comment by daarias331** [comment] 2023-09-27 01:55
Thank you @giohappy @mattiagiupponi for your prompt action.
I have tested the fix doing the following: Added the command at the end of the Docker file like this:
`pip install -e git+https://github.com/GeoNode/geonode-importer.git@ISSUE_207#egg=geonode-importer` 
Then rebuilding the whole project using:
`docker-compose -f docker-compose.yml build --no-cache

docker-compose -f docker-compose.yml up -d
`

I can confirm that the layer's data is now being updated. Nevertheless, the thumbnail remains the same as before.

**Comment by daarias331** [comment] 2023-09-27 06:56
Good morning,

I have done more testing (this time with raster .tiff and .tif) and the result is a duplicate layer instead of overwriting the first layer, despite having specified **overwrite_existing_layer** = **True** in the API call.

I attached the two layers I used for testing. The first layer you see is the one to be overwritten. The layer inside the folder **"updated"** is the one to use to overwrite the first layer.

Let me know if you prefer that I open another issue with this specific problem with the rasters.

[test_raster1.zip](https://github.com/GeoNode/geonode/files/12735383/test_raster1.zip)

**Comment by mattiagiupponi** [comment] 2023-09-27 07:20
Hi @daarias331 
Thanks for the checks, i'll give a check on both issues.
No need to oepn another issue since is always related to the overwrite flow.

I'll give a check as soon as possible

**Comment by daarias331** [comment] 2023-09-28 04:29
Hi @mattiagiupponi 
I have tested both raster and vector and can confirm that they are working as expected., including the update of the thumbnail.

Thanks again for your prompt response

**Comment by mattiagiupponi** [comment] 2023-09-28 07:48
Hi @daarias331 
Thanks for the feedback. I'm going to open a PR on the importer library. I guess the new version of the importer will be released along with GeoNode 4.2.0, but @giohappy can give more info about it

**Comment by mattiagiupponi** [comment] 2023-10-03 12:39
Fix has been merged into the geonode-importer repo. The fix is now avalable on master branch.
A new version of the importer will be released along with geonode 4.2.0

**Closed by mattiagiupponi** 2023-10-03 12:39 UTC
Labels: needs further investigation, 4.1.x
