### ISSUE TITLE
Installation Issue in Geonode 2.4 Windows Installer

### ISSUE THREAD

**Issue by piyush-shah** [GeoNode/geonode#2421] opened 2016-02-10 14:25 UTC
Hi,

I am trying to install Geonode 2.4 through Windows Installer (which is recently updated on Geonode website) on Windows 10 and Windows 8.1 operating system but I am failed both the time.

Both the time I face the same issue "postgres SQL 8.4.22 database server not installed properly or not started the database server service".

So can anyone help me to identify what wrong I am doing in that and how can I solve it, I had refereed the Window Binary Installer `[Geonode doc](http://docs.geonode.org/en/latest/tutorials/install_and_admin/win_bin_install/win_binary_installer.html#win-binary-installer)` for installation process.

Thank you in advance.

Regards,
Piyush

**Comment by afabiani** [comment] 2016-02-12 09:20
Dear piyush,
I'm working on an improvement of the installer allowing it to ask for a
port and path different from the default ones.

Please be patient. I will provide you and updated version of the installer
as soon as possible.

Best Regards,
Alessio Fabiani.

==
GeoServer Professional Services from the experts!
Visit http://goo.gl/it488V for more information.
==

Ing. Alessio Fabiani
@alfa7691
Founder/Technical Lead

GeoSolutions S.A.S.
Via di Montramito 3/A
55054  Massarosa (LU)
Italy
phone: +39 0584 962313
fax:     +39 0584 1660272
mob:   +39 333 8128928

http://www.geo-solutions.it
http://twitter.com/geosolutions_it

-------------------------------------------------------

*AVVERTENZE AI SENSI DEL D.Lgs. 196/2003*

Le informazioni contenute in questo messaggio di posta elettronica e/o
nel/i file/s allegato/i sono da considerarsi strettamente riservate. Il
loro utilizzo è consentito esclusivamente al destinatario del messaggio,
per le finalità indicate nel messaggio stesso. Qualora riceviate questo
messaggio senza esserne il destinatario, Vi preghiamo cortesemente di
darcene notizia via e-mail e di procedere alla distruzione del messaggio
stesso, cancellandolo dal Vostro sistema. Conservare il messaggio stesso,
divulgarlo anche in parte, distribuirlo ad altri soggetti, copiarlo, od
utilizzarlo per finalità diverse, costituisce comportamento contrario ai
principi dettati dal D.Lgs. 196/2003.



The information in this message and/or attachments, is intended solely for
the attention and use of the named addressee(s) and may be confidential or
proprietary in nature or covered by the provisions of privacy act
(Legislative Decree June, 30 2003, no.196 - Italy's New Data Protection
Code).Any use not in accord with its purpose, any disclosure, reproduction,
copying, distribution, or either dissemination, either whole or partial, is
strictly forbidden except previous formal approval of the named
addressee(s). If you are not the intended recipient, please contact
immediately the sender by telephone, fax or e-mail and delete the
information in this message that has been received in error. The sender
does not give any warranty or accept liability as the content, accuracy or
completeness of sent messages and accepts no responsibility  for changes
made after they were sent or for other risks which arise as a result of
e-mail transmission, viruses, etc.

---------------------------------------------------------------------

**Comment by piyush-shah** [comment] 2016-02-12 10:14
Thank you afabiani for your reply !

I am eagerly waiting for it.

Thanks & Regards,
Piyush

**Comment by afabiani** [comment] 2016-02-17 11:25
Hello,

I just updated the Windows Installer

http://build.geonode.org/windows/GeoNode-2.4.x.exe

allowing it to installa PostgreSQL on a port different from the default one
5432 -> 5454 and using a strong password.


Best Regards,
Alessio Fabiani.

==
GeoServer Professional Services from the experts!
Visit http://goo.gl/it488V for more information.
==

Ing. Alessio Fabiani
@alfa7691
Founder/Technical Lead

GeoSolutions S.A.S.
Via di Montramito 3/A
55054  Massarosa (LU)
Italy
phone: +39 0584 962313
fax:     +39 0584 1660272
mob:   +39 333 8128928

http://www.geo-solutions.it
http://twitter.com/geosolutions_it

-------------------------------------------------------

*AVVERTENZE AI SENSI DEL D.Lgs. 196/2003*

Le informazioni contenute in questo messaggio di posta elettronica e/o
nel/i file/s allegato/i sono da considerarsi strettamente riservate. Il
loro utilizzo è consentito esclusivamente al destinatario del messaggio,
per le finalità indicate nel messaggio stesso. Qualora riceviate questo
messaggio senza esserne il destinatario, Vi preghiamo cortesemente di
darcene notizia via e-mail e di procedere alla distruzione del messaggio
stesso, cancellandolo dal Vostro sistema. Conservare il messaggio stesso,
divulgarlo anche in parte, distribuirlo ad altri soggetti, copiarlo, od
utilizzarlo per finalità diverse, costituisce comportamento contrario ai
principi dettati dal D.Lgs. 196/2003.



The information in this message and/or attachments, is intended solely for
the attention and use of the named addressee(s) and may be confidential or
proprietary in nature or covered by the provisions of privacy act
(Legislative Decree June, 30 2003, no.196 - Italy's New Data Protection
Code).Any use not in accord with its purpose, any disclosure, reproduction,
copying, distribution, or either dissemination, either whole or partial, is
strictly forbidden except previous formal approval of the named
addressee(s). If you are not the intended recipient, please contact
immediately the sender by telephone, fax or e-mail and delete the
information in this message that has been received in error. The sender
does not give any warranty or accept liability as the content, accuracy or
completeness of sent messages and accepts no responsibility  for changes
made after they were sent or for other risks which arise as a result of
e-mail transmission, viruses, etc.

---------------------------------------------------------------------

**Comment by jj0hns0n** [comment] 2016-08-21 06:42
@piyush-shah @afabiani can we close this now?

**Comment by afabiani** [comment] 2016-08-21 11:14
I guess we can close this.

If other issues with the Wind installer will rise up, we will address them
on specific issues.

Best Regards,
Alessio Fabiani.

==
GeoServer Professional Services from the experts!
Visit http://goo.gl/it488V for more information.
==

Ing. Alessio Fabiani
@alfa7691
Founder/Technical Lead

GeoSolutions S.A.S.
Via di Montramito 3/A
55054  Massarosa (LU)
Italy
phone: +39 0584 962313
fax:     +39 0584 1660272
mob:   +39 331 6233686

http://www.geo-solutions.it
http://twitter.com/geosolutions_it

-------------------------------------------------------

*AVVERTENZE AI SENSI DEL D.Lgs. 196/2003*

Le informazioni contenute in questo messaggio di posta elettronica e/o
nel/i file/s allegato/i sono da considerarsi strettamente riservate. Il
loro utilizzo è consentito esclusivamente al destinatario del messaggio,
per le finalità indicate nel messaggio stesso. Qualora riceviate questo
messaggio senza esserne il destinatario, Vi preghiamo cortesemente di
darcene notizia via e-mail e di procedere alla distruzione del messaggio
stesso, cancellandolo dal Vostro sistema. Conservare il messaggio stesso,
divulgarlo anche in parte, distribuirlo ad altri soggetti, copiarlo, od
utilizzarlo per finalità diverse, costituisce comportamento contrario ai
principi dettati dal D.Lgs. 196/2003.



The information in this message and/or attachments, is intended solely for
the attention and use of the named addressee(s) and may be confidential or
proprietary in nature or covered by the provisions of privacy act
(Legislative Decree June, 30 2003, no.196 - Italy's New Data Protection
Code).Any use not in accord with its purpose, any disclosure, reproduction,
copying, distribution, or either dissemination, either whole or partial, is
strictly forbidden except previous formal approval of the named
addressee(s). If you are not the intended recipient, please contact
immediately the sender by telephone, fax or e-mail and delete the
information in this message that has been received in error. The sender
does not give any warranty or accept liability as the content, accuracy or
completeness of sent messages and accepts no responsibility  for changes
made after they were sent or for other risks which arise as a result of
e-mail transmission, viruses, etc.

---------------------------------------------------------------------

**Closed** 2016-08-21 11:14 UTC
Labels: bug, windows

**Comment by piyush-shah** [comment] 2016-08-22 14:06
Yes, I had successful installed the geonode instance on my windows machine Piyush M ShahGIS Professional
M.Sc (Geomatics and Space Application), M.Sc (IT and CA)Phone: +91-79-22860917Mobile: 09408721451 

    On Sunday, 21 August 2016 4:44 PM, Alessio Fabiani <notifications@github.com> wrote:
 

 I guess we can close this.

If other issues with the Wind installer will rise up, we will address them
on specific issues.

Best Regards,
Alessio Fabiani.

==
GeoServer Professional Services from the experts!
Visit http://goo.gl/it488V for more information.
==

Ing. Alessio Fabiani
@alfa7691
Founder/Technical Lead

GeoSolutions S.A.S.
Via di Montramito 3/A
55054 Massarosa (LU)
Italy
phone: +39 0584 962313
fax: +39 0584 1660272
mob: +39 331 6233686

http://www.geo-solutions.it
http://twitter.com/geosolutions_it

-------------------------------------------------------

*AVVERTENZE AI SENSI DEL D.Lgs. 196/2003*

Le informazioni contenute in questo messaggio di posta elettronica e/o
nel/i file/s allegato/i sono da considerarsi strettamente riservate. Il
loro utilizzo è consentito esclusivamente al destinatario del messaggio,
per le finalità indicate nel messaggio stesso. Qualora riceviate questo
messaggio senza esserne il destinatario, Vi preghiamo cortesemente di
darcene notizia via e-mail e di procedere alla distruzione del messaggio
stesso, cancellandolo dal Vostro sistema. Conservare il messaggio stesso,
divulgarlo anche in parte, distribuirlo ad altri soggetti, copiarlo, od
utilizzarlo per finalità diverse, costituisce comportamento contrario ai
principi dettati dal D.Lgs. 196/2003.



The information in this message and/or attachments, is intended solely for
the attention and use of the named addressee(s) and may be confidential or
proprietary in nature or covered by the provisions of privacy act
(Legislative Decree June, 30 2003, no.196 - Italy's New Data Protection
Code).Any use not in accord with its purpose, any disclosure, reproduction,
copying, distribution, or either dissemination, either whole or partial, is
strictly forbidden except previous formal approval of the named
addressee(s). If you are not the intended recipient, please contact
immediately the sender by telephone, fax or e-mail and delete the
information in this message that has been received in error. The sender
does not give any warranty or accept liability as the content, accuracy or
completeness of sent messages and accepts no responsibility for changes
made after they were sent or for other risks which arise as a result of
e-mail transmission, viruses, etc.

---------------------------------------------------------------------

**Comment by Baju3D** [comment] 2018-10-30 09:58
Thank you for your information.

**Comment by suongsovann** [comment] 2018-12-09 17:36
I can not download "The GeoNode Windows Binary installer", so how can I do?

**Comment by Baju3D** [comment] 2018-12-11 04:07
Suongsovann, you can download from this link  

https://ucb03f15ea4e1f2336c5b7875bd2.dl.dropboxusercontent.com/cd/0/get/AWOR-BWwk5ToYOU4VYMGotCOmps6Emj_JsrsWlY565_22kRDOOG4ixBuT_MA0QDUnw7oMHRn25Dq9LKhxIRvFsKEATy51GhtAqD4FfUlBfHV2A76R0-MuqlIxo6r4f9Ejh9iAlrIQODWj-NX-q9njGoeOYEAZgwfH5wxSmDsmtlzPLqelLrgcqk1WfZkgT4asH0/file?_download_id=60232639028818069579085273689913158147131258169935862683523822505&_notify_domain=www.dropbox.com&dl=1

**Comment by Baju3D** [comment] 2018-12-11 06:12
Sovan, try this link. I hope this one will success.

https://www.dropbox.com/s/ujclwt7mtu5zy87/GeoNode-2.4.exe?dl=0

from Jakarta Indonesia.

**Comment by suongsovann** [comment] 2018-12-11 08:40
Dear Muhammad,


Many thanks for your email, I have setup with Windows 10, but it is error
some file, so it is not work, do you have any version that can run with OS
10?, could you please give me a line as possible.


Regards,

SOVAN

**Comment by Shovon89** [comment] 2025-02-18 11:05
Dear Sir,
I could not find the file https://www.dropbox.com/s/ujclwt7mtu5zy87/GeoNode-2.4.exe?dl=0  from this link. It says the file has been deleted, could you please share the updated one? I'm trying to install GeoNode on Windows 11 pro.

Thanks
