### ISSUE TITLE
Geonode groups not visible in the UI

### ISSUE THREAD

**Issue by akudekar** [GeoNode/geonode#6374] opened 2020-08-24 11:56 UTC
## Expected Behavior

Groups should be visible from the UI and Django admin panel

## Actual Behavior

Groups not visible in the UI. But can be seen on the Django admin panel. 

<img width="956" alt="Annotation 2020-08-24 135537" src="https://user-images.githubusercontent.com/50870889/91042107-8a755800-e611-11ea-8bfe-f899979eb0da.png">

## Specifications

  - GeoNode version: 3
  - Installation method - Docker
  - Platform: Linux
  - Additional details:

**Comment by t-book** [comment] 2020-08-24 16:15
@akudekar can you try to delete your browser cache? Does the issue remain?

**Comment by akudekar** [comment] 2020-08-24 17:03
@t-book nope, clearing browser cache didn't help. The issue still remains.

**Comment by t-book** [comment] 2020-08-24 17:30
@akudekar is it spc docker or the regular stack?

**Comment by akudekar** [comment] 2020-08-24 20:15
@t-book its a regular stack docker running on Linux

**Comment by t-book** [comment] 2020-08-25 07:22
@akudekar I cannot reproduce. This is how I tested:

1. git clone https://github.com/GeoNode/geonode.git
2. vi .env -> SET_DOCKER_ENV=development
3. docker-compose -f docker-compose.async.yml -f docker-compose.development.yml up

Result:

I can see following error or warning.
<img width="1552" alt="Bildschirmfoto 2020-08-25 um 09 18 55" src="https://user-images.githubusercontent.com/20478652/91144432-4f783080-e6b4-11ea-9c08-4aba700ed5ac.png">
Nevertheless the registered Group is successfully shown 

After creating a new group.
<img width="1329" alt="Bildschirmfoto 2020-08-25 um 09 19 22" src="https://user-images.githubusercontent.com/20478652/91144522-7171b300-e6b4-11ea-9928-0907d1901c13.png">
The Group is shown and the total count is correct.

**Comment by akudekar** [comment] 2020-08-25 08:47
@t-book yep the unhandled rejection is not causing any problems for me either. I will test some more and see if restarting the container works. The thing is, I wasn’t able to reproduce the error either

**Comment by t-book** [comment] 2020-08-25 09:41
@akudekar closing here. please reopen in case this needs further work.

**Closed by t-book** 2020-08-25 09:41 UTC
Labels: frontend, needs further investigation

**Comment by jannefleischer** [comment] 2020-08-28 15:35
As @akudekar is leaving the company I am now trying to fix this issue.
And I must correct him, as the geonode in question isn't our docker based deployment but the "old" 2.10.4 that has grown from 2.6 to 2.10.0 to 2.10.4 (last one recently, as @t-book know). Sorry for the miscommunication.

I dig deeper into this issue and learned that search.js wouldn't receive any data from foo.com/api/groups. 
foo.com/api/groups just gives back the (empty) foo.com/groups page instead of a well formed .json as foo.com/api/users or foo.com/api/layers would give.

Sadly I couldn't figure out if this an obscurity of our sometimes buggyish 2.10.4-Geonode or a general issue with 2.10.4. In our 3.0-in-prep Docker the api reports correct. Could someone give a feedback if its a general 2.10.4-issue or if I should dig deeper into our special case? Thanks!

In case anyone knows: Where should I look for a urls.py (or a file that have the same function) where an entry for the api could be missing? I briefly checked the geonode 3.0 source code in comparisson to the 2.10.4: the several urls.py seem to look the same... despite the 3 shows the api/groups...

**Comment by t-book** [comment] 2020-08-28 17:12
@jannefleischer I know the answer and will close here. Will write you a pm @ gitter
