### ISSUE TITLE
Missing OGC reference metadata

### ISSUE THREAD

**Issue by JinIgarashi** [GeoNode/geonode#7306] opened 2021-04-15 08:23 UTC
When I create a map and try to add new layer, there is an error message `Missing OGC reference metadata` occurred. 

![image](https://user-images.githubusercontent.com/2639701/114837289-800d0600-9e0e-11eb-89b9-c8099b046439.png)

Uploading was successful, the new layer was also added in Geoserver.

I found the same error in OSGEO Live in this page.

http://osgeo-org.1560.x6.nabble.com/Problem-GeoNode-OSGeoLive-13-0-Missing-OGC-reference-metadata-td5437840.html

I think some configuration of GeoNode is missing, but I am not sure the reason...
Do you have any idea to resolve this issue?

## Steps to Reproduce the Problem

 - Install GeoNode in Ubuntu by following [basic installation](https://docs.geonode.org/en/master/install/basic/index.html) procedure.
- Upload an layer to GeoNode
- Select `Create Map`
- Select `Add layer`

## Specifications

  - GeoNode version:3.2.x
  - Installation method (manual, GeoNode Docker, SPCGeoNode Docker):GeoNode Docker
  - Platform: Ubuntu 20.04, AWS EC2
  - Additional details:

**Comment by giohappy** [comment] 2021-04-30 15:05
@JinIgarashi can you test the upload of your sample layer on the [demo instance](https://master.demo.geonode.org/)?.
3.2.x is affected by a regression caused by a side effect in a change to the CSW service. The fix is on its way to be pushed, but in your case it looks like you're talking of layers. Is it?

**Comment by JinIgarashi** [comment] 2021-04-30 23:30
@giohappy thanks. I think the issue is not my data of layers. I believe some of my configurations are not well, because the layers uploaded are working very well in geoserver. If the problem is data itself, I think it can not be uploaded to geoserver and postgis.

**Comment by giohappy** [comment] 2021-06-03 14:09
@JinIgarashi the filtering of CSW responses has been fixed in GeoNode 3.2.x. Now only layers (with OGC reference metadata) should be visible.
I'm going to close this. In case the issue is still there you can repoen it.

**Closed by giohappy** 2021-06-03 14:09 UTC

**Comment by t-book** [comment] 2021-11-15 10:58
@giohappy I'm having this issue on a 3.0 instance as well. Can you provide a little more background on what goes wrong? As the described layers with missing OGC reference cannot be added to maps. What suprises: Looking at the `/catalogue/csw?service=CSW&version=2.0.2` response I can see that the layer in questions has `<dc:identifier>9a507c98-b1c2-11e4-8547-0050569a7363</dc:identifier>` set which should be used as identifier? What is unclear to me is why this value is marked as missing on only some layers.

**Comment by giohappy** [comment] 2021-11-15 11:27
@t-book the following is an example of a working record. The relevant element here is `<dct:references scheme="OGC:WMS">https://development.demo.geonode.org/geoserver/ows</dct:references>`. This is what the client needs to make the WMS request.

If it's missing either it's not a valid record type (i.e. and this shouldn't happen since the CSW filter should only return valid records) or the layer's links are not populated (some inconsistency in the stored data).

```
<csw:Record>
  <dc:identifier>3eb18014-40a7-11ec-b161-0242c0a8e004</dc:identifier>
  <dc:title>Meteorite_Landings_from_NASA_Open_Data_Portal</dc:title>
  <dc:type>dataset</dc:type>
  <dc:subject></dc:subject>
  <dct:references scheme="WWW:DOWNLOAD-1.0-http--download">https://development.demo.geonode.org/uploaded/thumbs/layer-3eb18014-40a7-11ec-b161-0242c0a8e004-thumb-83069cfb-a332-4253-9d4f-38ebfa9c9b5d.png</dct:references>
  <dct:references scheme="WWW:DOWNLOAD-1.0-http--download">https://development.demo.geonode.org/geoserver/ows?service=WMS&amp;request=GetMap&amp;layers=geonode%3AMeteorite_Landings_from_NASA_Open_Data_Portal&amp;format=image%2Fpng&amp;height=550&amp;width=1696&amp;srs=EPSG%3A4326&amp;bbox=-165.4333038330078%2C-87.36670684814453%2C354.47332763671875%2C81.16670227050781</dct:references>
  <dct:references scheme="WWW:DOWNLOAD-1.0-http--download">https://development.demo.geonode.org/geoserver/ows?service=WMS&amp;request=GetMap&amp;layers=geonode%3AMeteorite_Landings_from_NASA_Open_Data_Portal&amp;format=image%2Fjpeg&amp;height=550&amp;width=1696&amp;srs=EPSG%3A4326&amp;bbox=-165.4333038330078%2C-87.36670684814453%2C354.47332763671875%2C81.16670227050781</dct:references>
  <dct:references scheme="WWW:DOWNLOAD-1.0-http--download">https://development.demo.geonode.org/geoserver/ows?service=WMS&amp;request=GetMap&amp;layers=geonode%3AMeteorite_Landings_from_NASA_Open_Data_Portal&amp;format=application%2Fpdf&amp;height=550&amp;width=1696&amp;srs=EPSG%3A4326&amp;bbox=-165.4333038330078%2C-87.36670684814453%2C354.47332763671875%2C81.16670227050781</dct:references>
  <dct:references scheme="WWW:DOWNLOAD-1.0-http--download">https://development.demo.geonode.org/download/106</dct:references>
  <dct:references scheme="WWW:DOWNLOAD-1.0-http--download">https://development.demo.geonode.org/geoserver/ows?service=WFS&amp;version=1.0.0&amp;request=GetFeature&amp;typename=geonode%3AMeteorite_Landings_from_NASA_Open_Data_Portal&amp;outputFormat=excel&amp;srs=EPSG%3A4326</dct:references>
  <dct:references scheme="WWW:DOWNLOAD-1.0-http--download">https://development.demo.geonode.org/geoserver/ows?service=WFS&amp;version=1.0.0&amp;request=GetFeature&amp;typename=geonode%3AMeteorite_Landings_from_NASA_Open_Data_Portal&amp;outputFormat=json&amp;srs=EPSG%3A4326&amp;srsName=EPSG%3A4326</dct:references>
  <dct:references scheme="WWW:DOWNLOAD-1.0-http--download">https://development.demo.geonode.org/geoserver/ows?service=WFS&amp;version=1.0.0&amp;request=GetFeature&amp;typename=geonode%3AMeteorite_Landings_from_NASA_Open_Data_Portal&amp;outputFormat=SHAPE-ZIP&amp;srs=EPSG%3A4326&amp;format_options=charset%3AUTF-8</dct:references>
  <dct:references scheme="WWW:DOWNLOAD-1.0-http--download">https://development.demo.geonode.org/geoserver/ows?service=WFS&amp;version=1.0.0&amp;request=GetFeature&amp;typename=geonode%3AMeteorite_Landings_from_NASA_Open_Data_Portal&amp;outputFormat=gml2&amp;srs=EPSG%3A4326</dct:references>
  <dct:references scheme="WWW:DOWNLOAD-1.0-http--download">https://development.demo.geonode.org/geoserver/ows?service=WFS&amp;version=1.0.0&amp;request=GetFeature&amp;typename=geonode%3AMeteorite_Landings_from_NASA_Open_Data_Portal&amp;outputFormat=text%2Fxml%3B+subtype%3Dgml%2F3.1.1&amp;srs=EPSG%3A4326</dct:references>
  <dct:references scheme="WWW:DOWNLOAD-1.0-http--download">https://development.demo.geonode.org/geoserver/ows?service=WFS&amp;version=1.0.0&amp;request=GetFeature&amp;typename=geonode%3AMeteorite_Landings_from_NASA_Open_Data_Portal&amp;outputFormat=csv&amp;srs=EPSG%3A4326</dct:references>
  <dct:references scheme="WWW:LINK-1.0-http--link">https://development.demo.geonode.org/layers/geonode_demo_data:geonode:Meteorite_Landings_from_NASA_Open_Data_Portal</dct:references>
  <dct:references scheme="WWW:DOWNLOAD-1.0-http--download">https://development.demo.geonode.org/geoserver/ows?service=WMS&amp;request=GetLegendGraphic&amp;format=image/png&amp;WIDTH=20&amp;HEIGHT=20&amp;LAYER=geonode:Meteorite_Landings_from_NASA_Open_Data_Portal&amp;STYLE=Meteorite_Landings_from_NASA_Open_Data_Portal&amp;version=1.3.0&amp;sld_version=1.1.0&amp;legend_options=fontAntiAliasing:true;fontSize:12;forceLabels:on</dct:references>
  <dct:references scheme="OGC:WMS">https://development.demo.geonode.org/geoserver/ows</dct:references>
  <dct:references scheme="OGC:WFS">https://development.demo.geonode.org/geoserver/ows</dct:references>
  <dct:modified>2021-11-08T15:19:19Z</dct:modified>
  <dct:abstract>No abstract provided</dct:abstract>
  <dc:date>2021-11-08T15:19:19Z</dc:date>
  <dc:creator>admin</dc:creator>
  <dc:publisher>admin</dc:publisher>
  <dc:contributor>admin</dc:contributor>
  <dc:language>eng</dc:language>
  <dct:alternative>geonode:Meteorite_Landings_from_NASA_Open_Data_Portal</dct:alternative>
  <dct:spatial scheme="http://www.opengis.net/def/crs">EPSG:4326</dct:spatial>
  <ows:BoundingBox crs="urn:x-ogc:def:crs:EPSG:6.11:4326" dimensions="2">
    <ows:LowerCorner>-87.36670684814453 -165.4333038330078</ows:LowerCorner>
    <ows:UpperCorner>81.16670227050781 354.4733276367188</ows:UpperCorner>
  </ows:BoundingBox>
</csw:Record>
```

**Comment by t-book** [comment] 2021-11-15 12:39
Thanks a lot, @giohappy this makes things a bit clearer. I guess it's hard to say why it's failing one time and next time it works with the exact same layer. 

But can you say do we have a management command to set this element again or do you know in which model field the element is stored (I could then just fix it manually for now)?

**Comment by t-book** [comment] 2021-11-15 12:51
@giohappy think I found it -> https://github.com/GeoNode/geonode/blob/master/geonode/base/models.py#L1546-L1576

**Comment by t-book** [comment] 2021-11-15 14:32
@giohappy ha -> https://github.com/GeoNode/geonode/issues/8198 thank you twice ;))
