### ISSUE TITLE
Problem with Installation 2.10 GeoNode on Ubuntu 18.04.3 LTS

### ISSUE THREAD

**Issue by neroznik** [GeoNode/geonode#5042] opened 2019-10-14 12:15 UTC
Good day!
I am  trying install Geonode 2.10 by Docker firs time on new server.

After 
`docker-compose -f docker-compose.yml -f docker-compose.override.localhost.yml up -d`

I have  

> Starting gsconf4geonode ...
> Starting gsconf4geonode
> Starting gsconf4geonode ... done
> django4geonode is up-to-date
> geoserver4geonode is up-to-date
> Starting 7898beb1f528_7898beb1f528_nginx4geonode ...
> Starting 7898beb1f528_7898beb1f528_nginx4geonode ... error
> 
> ERROR: for 7898beb1f528_7898beb1f528_nginx4geonode  Cannot start service geonode: driver failed programming external connectivity on endpoint 7898beb1f528_7898beb1f528_nginx4geonode (21347d00afb97745fe66994e5a98c70cfac3e27dbcdff8ec0383c27a5abacbc6): Error starting userland proxy: listen tcp 0.0.0.0:80: bind: address already in use
> 
> ERROR: for geonode  Cannot start service geonode: driver failed programming external connectivity on endpoint 7898beb1f528_7898beb1f528_nginx4geonode (21347d00afb97745fe66994e5a98c70cfac3e27dbcdff8ec0383c27a5abacbc6): Error starting userland proxy: listen tcp 0.0.0.0:80: bind: address already in use
> ERROR: Encountered errors while bringing up the project.

Unfortunately, I couldn't find solution. Can you please help me with this?

  - GeoNode version: 2.10
  - Installation method:  GeoNode Docker,
  - Platform: Ubuntu 18.04.3 LTS
  - Additional details: I am beginner in Geonode as well as GitHub

**Comment by gannebamm** [comment] 2019-10-14 13:08
Hi @neroznik 
There are some unknown issues with the default Docker Compose installation. Would you please try to use the SPC Geonode installation instead?

You can start it by doing the following steps:

1. navigate to /scripts/spcgeonode
2. edit `.env` file to fit your config (eg change the hosts ip)
3. Run and build the stack with `docker-compose -f docker-compose.yml -f docker-compose.override.yml up --build` and take a look at the console while the containers start and wait for each other. This will run the stack in debug mode.

If you want to modify it for production you should `docker-compose up --build` and change the `.env` passwords and stuff like that.

**Comment by gannebamm** [comment] 2019-10-14 13:09
> Error starting userland proxy: listen tcp 0.0.0.0:80: bind: address already in use

This looks like your docker-host allready uses port 80. Do you run an webserver on it? You have to switch to a different port then, see https://github.com/GeoNode/geonode/blob/master/scripts/spcgeonode/.env#L22

**Comment by t-book** [comment] 2019-10-15 16:59
I cannot reproduce this on a fresh xenial Ubuntu. It might be a configuration issue of your server. In case it is please consider using the user/dev list at OSGeo for help.

**Comment by gannebamm** [comment] 2019-10-17 08:43
I am unable to reproduce this issue, too.
closing this.

**Closed by gannebamm** 2019-10-17 08:43 UTC
Labels: docker, question
