### ISSUE TITLE
Cannot Edit Data in Layers Edit Data Menu 

### ISSUE THREAD

**Issue by achorivai** [GeoNode/geonode#7690] opened 2021-06-22 09:39 UTC
## Expected Behavior

![Screenshot 2021-06-22 at 16-30-38 New Map - Forest Programme III](https://user-images.githubusercontent.com/4677202/122901637-e9157a80-d377-11eb-8f83-aa9861372082.png)

## Actual Behavior
![Screenshot 2021-06-22 at 16-30-09 New Map - master demo geonode org](https://user-images.githubusercontent.com/4677202/122901657-ed419800-d377-11eb-9e55-bb56e7fd3112.png)

## Steps to Reproduce the Problem

  1. There is no Edit Option (Pencil Icon) when we choose Edit Data for Layers
  2.
  3.

## Specifications

  - GeoNode version: 3.2.0 
  - Installation method (GeoNode Docker, ): Docker
  - Platform: Ubuntu 20.4.x

  - Additional details:

**Comment by diegodoy** [comment] 2021-06-23 17:54
I have the same issue, whit the same specifications.

**Comment by afabiani** [comment] 2021-06-24 07:47
Are you using the 3.2.0 release or 3.2.x branch?

**Comment by diegodoy** [comment] 2021-06-24 07:56
Hello Alessio.
Yes. I think so.

https://www.ide.posadas.gob.ar/

Thanks for your attention.

Regards.

**Comment by afabiani** [comment] 2021-06-24 08:10
@diegodoy can you give me some more details on how you deployed it? The error here seems a version conflict between the mapstore-client and geonode. The client is looking for some deprecated methods that exist on 3.2.0 but have been removed on 3.2.x

**Comment by diegodoy** [comment] 2021-06-29 21:20
@afabiani Thanks for you answer. We finanally had to do a prune, reinstall all again and restore the databases using postgres pg_restore.  We made a serveral recopilations of all, but didn't work.

**Comment by afabiani** [comment] 2021-06-30 08:16
@diegodoy probably I was not clear enough, in order to check the consistency between geonode and mapstore-client I need to know:

1. How you deployed geonode? Which branch you used? I see in the description of the issue you are using Docker, from the core directly?
2. Can you provide a print of the "requirements.txt" file so I can understand which version of the "mapstore-client" you are currently using?

**Comment by afabiani** [comment] 2021-07-01 09:56
So far I have been able to reproduce this issue.
Basically you are using GeoNode from branch 3.2.x and the geonode-mapstore-client from Pypi, version 2.1.4.

This problem is fixed on the geonode-mapstore-client branch 2.1.x

You have two options:

1. Install the geonode-mapstore-client from the source code
2. Wait for the next GeoNode 3.2.1 and geonode-mapstore-client stable releases

**Closed by afabiani** 2021-07-01 09:56 UTC
Labels: wontfix

**Comment by diegodoy** [comment] 2021-07-02 12:30
Thanks for your advice. Fortunately the problem was resolved. I will wait for 3.2.1 to upgrade.
