### ISSUE TITLE
Shapefile download should include the metadata as .xml and styles as .sld

### ISSUE THREAD

**Issue by vdeparday** [GeoNode/geonode#1972] opened 2015-02-02 17:03 UTC
It requires two separate downloads to get the shp and xml and it is not possible to download the style without going through GeoServer

It would require either to add it in core GeoServer or to implement or to package on the Django side.

**Comment by state-hiu** [comment] 2015-02-02 19:56
For GeoServer, I think we'd need to add some additional parameters.

http://docs.geoserver.org/latest/en/user/services/wfs/outputformats.html#wfs-outputformat-shapezip

**Comment by JJediny** [comment] 2015-02-02 23:41
Packaging a zip from three end points in 1. geoserver WFS (data) 2. geoserver REST (sld) 3. pyCSW (xml) Seems like a lot to resolve while only supporting shapefile. Think an interim solution would be to list the same available (data/metadata/style) downloads for the layer in the same download popup so user could atleast download all from same screen? Download Sld requires authentication

**Comment by jj0hns0n** [comment] 2015-02-03 09:37
Partial Dupe of https://github.com/GeoNode/geonode/issues/1240

**Comment by ingenieroariel** [comment] 2015-02-04 18:49
we should create a feature request to geoserver for an optional parameter to get the sld into the zip file.

**Comment by ischneider** [comment] 2015-02-04 21:04
As noted in #1240, I believe this is actually done in geoserver-geonode-ext:
https://github.com/GeoNode/geoserver-geonode-ext/blob/master/src/main/java/org/geonode/process/batchdownload/shp/ShapeZipWriter.java

**Closed** 2018-05-22 07:50 UTC
Labels: download, geoserver-integration, layers
