### ISSUE TITLE
Wrong rules are added to geofence after uploading a new layer in Geonode

### ISSUE THREAD

**Issue by gioman** [GeoNode/geonode#7351] opened 2021-04-20 07:59 UTC
Seen this on both Geonode 3.1 and 3.2

When making a layer protected in Geonode (by allowing its access/download only to users with credentials and removing the anonymous access) it is expected that those layer to not show in the GetCapabilities of the WMS,WFS and WCS services when accessed via https://url/gs/ows

For WFS this works fine, but for WMS and WCS this do not happens, and the protected layers always show in capabilities of WMS and WCS also for anonymous users, and they can even download/getmap those layers.

It happens that the problem is that a rule (one for WMS and one of WCS) is added to Geoserver/geofence every time a layer is added in Geonode, and this rules allows access to all layers via WMS/WCS to everyone. Removing manually the rule "fixes" the problem, but as soon a new layer is uploaded in Geonode the problem is back.

**Comment by gioman** [comment] 2021-04-20 13:47
@afabiani as requested


1) the wrong rule is in geofence

![Screenshot_20210420_143419](https://user-images.githubusercontent.com/1951107/115406094-c2578e00-a1e6-11eb-94b5-84071471be1f.png)

2) Layer is protected

![Screenshot_20210420_143323](https://user-images.githubusercontent.com/1951107/115406372-0480cf80-a1e7-11eb-8918-533e8d622c01.png)

3) layers shows in getcapabilities

![Screenshot_20210420_143357](https://user-images.githubusercontent.com/1951107/115406430-12365500-a1e7-11eb-95d6-ee837b14e106.png)

4) rule is removed

![Screenshot_20210420_143451](https://user-images.githubusercontent.com/1951107/115406455-195d6300-a1e7-11eb-9924-8b138e18d9a5.png)

5) protected layer disappear, as expected, from capabilities

![Screenshot_20210420_143516](https://user-images.githubusercontent.com/1951107/115406502-28441580-a1e7-11eb-9ce3-f2b0115e15b2.png)

6) a new layer is loaded

![Screenshot_20210420_143844](https://user-images.githubusercontent.com/1951107/115406528-2ed28d00-a1e7-11eb-9bbb-c76e6f394cf0.png)

7) wrong rule is back

![Screenshot_20210420_144100](https://user-images.githubusercontent.com/1951107/115406564-342fd780-a1e7-11eb-8c13-782c9ef25ca5.png)

**Comment by giohappy** [comment] 2021-04-20 14:04
@gioman I couldn't replicate it locally? What happens if you remove those rules manually and create a new layer again?

**Comment by gioman** [comment] 2021-04-20 14:47
> @gioman I couldn't replicate it locally?

@giohappy is a question or a statement?

I can replicate on 3.1 and 3.2 installed with https://docs.geonode.org/en/master/install/basic/  and without changing anything in the Geoserver control panel



> What happens if you remove those rules manually and create a new layer again?

that wrong rules (for WMS and WCS but not for WFS) are recreated automatically (as explained here above).

**Comment by giohappy** [comment] 2021-04-21 08:35
That's really strange @gioman, Both me and @afabiani couldn't reproduce this.
@t-book @gannebamm could you also try?

**Comment by t-book** [comment] 2021-04-21 10:19
@giohappy just tested. cannot reproduce.

**Comment by gioman** [comment] 2021-04-21 18:38
@giohappy @t-book @afabiani well of course you can't replicate, it is a classic: the user has issues and the dev/tester can't replicate :-)

I tried on fresh/new 3.1 and 3.2 installations, I can't replicate either.

But I definitely have a 3.1 installation (docker, ubuntu server 20.04) done a few weeks ago were the issue is easy to replicate. 

![Screenshot_20210421_193527](https://user-images.githubusercontent.com/1951107/115603998-c237bb00-a2d8-11eb-985e-7bda067c3829.png)

the above rules keep show up at each layer load (after having being deleted). No manual configurations in Geoserver control panel have been made.

I cannot unfortunately grant access to this instance, but if any of you is interested in investigating this we could some kind of remote session so I can show you the issue live. If there is no interest then I guess you can close this as "won't fix".

**Comment by gannebamm** [comment] 2021-04-21 19:03
I will try to replicate tomorrow.

**Comment by gioman** [comment] 2021-04-21 19:06
Thanks all for the effort.

**Comment by afabiani** [comment] 2021-04-22 07:10
@gioman can you make sure geonode is updated into your docker image to the latest commits?

**Comment by gioman** [comment] 2021-04-22 11:06
> @gioman can you make sure geonode is updated into your docker image to the latest commits?

@afabiani is this procedure https://docs.geonode.org/en/master/install/basic/#update-geonode-core-to-the-latest-commit rock solid? :)

**Comment by afabiani** [comment] 2021-04-22 12:23
@gioman yeps but there something is missing (we should add to the docs too).

You will need to update the celery container too. Problem is that for celery the `touch` procedure won't work. You will need to restart it:

`docker-compose restart celery`

**Comment by geoPM1** [comment] 2021-10-01 14:10
Hi. Did this issue ever get reproduced?

**Comment by gioman** [comment] 2021-10-01 14:11
> Hi. Did this issue ever get reproduced?

@geoPM1 well, I was able to replicate 100% of times on that particular installation. But then I didn't had more time to investigate/test more.

**Comment by geoPM1** [comment] 2021-10-01 14:14
@gioman Thanks for the update.

**Comment by afabiani** [comment] 2021-10-01 14:18
It should be fixed already on the current branches

**Comment by marlowp** [comment] 2021-10-01 14:32
Hi @afabiani, are you able to link to the fix for this? Or the general area of the code where this issue occurred? Thanks in advance!

**Comment by afabiani** [comment] 2021-10-01 14:43
Uhm, if you are using 3.2 already I strongly suggest to just update to the 3.2.x code, it contains major fixes that are useful in general.

If you plan to update it, the only things to update are:

### Celery Command Update
**issue**: The celery upload tasks make use of Celery `chord` which is not available on `FileBasedStores`

**solution**: From now on, on every setup based on 3.2.x, 3.3.x, 4.0.0 please update the celery commands as follows.

```diff
diff --git a/src/celery-cmd b/src/celery-cmd
index 1aefd14..8d973dd 100644
--- a/src/celery-cmd
+++ b/src/celery-cmd
@@ -3,13 +3,13 @@
 # Luca Pasquali <luca.pasquali@geo-solutions.it>
 CELERY_BIN=${CELERY_BIN:-"$(which celery||echo celery)"}
 CELERY_APP=${CELERY_APP:-"geonode.celery_app:app"}
-CELERY__STATE_DB=${CELERY__STATE_DB:-"/mnt/volumes/statics/worker.state"}
+# CELERY__STATE_DB=${CELERY__STATE_DB:-"/mnt/volumes/statics/worker.state"}
 # expressed in KB
 CELERY__MAX_MEMORY_PER_CHILD=${CELERY__MAX_MEMORY_PER_CHILD:-"200000"}
 CELERY__AUTOSCALE_VALUES=${CELERY__AUTOSCALE_VALUES:-"2,4"}
 CELERY__MAX_TASKS_PER_CHILD=${CELERY__MAX_TASKS_PER_CHILD:-"10"}
 CELERY__OPTS=${CELERY__OPTS:-"--without-gossip --without-mingle -Ofair -B -E"}
-CELERY__BEAT_SCHEDULE=${CELERY__BEAT_SCHEDULE:-"/mnt/volumes/statics/celerybeat-schedule"}
+CELERY__BEAT_SCHEDULE=${CELERY__BEAT_SCHEDULE:-"django_celery_beat.schedulers:DatabaseScheduler"}
 CELERY__LOG_LEVEL=${CELERY__LOG_LEVEL:-"INFO"}
 CELERY__LOG_FILE=${CELERY__LOG_FILE:-"/var/log/celery.log"}
 CELERY__WORKER_NAME=${CELERY__WORKER_NAME:-"worker1@%h"}
@@ -17,6 +17,7 @@ CELERY__WORKER_CONCURRENCY=${CELERY__WORKER_CONCURRENCY:-"4"}

 $CELERY_BIN -A $CELERY_APP worker --autoscale=$CELERY__AUTOSCALE_VALUES \
     --max-memory-per-child=$CELERY__MAX_MEMORY_PER_CHILD $CELERY__OPTS \
-    --statedb=$CELERY__STATE_DB -s $CELERY__BEAT_SCHEDULE \
+    -s $CELERY__BEAT_SCHEDULE \
     --loglevel=$CELERY__LOG_LEVEL -n $CELERY__WORKER_NAME -f $CELERY__LOG_FILE \
     --concurrency=$CELERY__WORKER_CONCURRENCY --max-tasks-per-child=$CELERY__MAX_TASKS_PER_CHILD
+
diff --git a/src/celery.sh b/src/celery.sh
index 8e9df54..ff61916 100644
--- a/src/celery.sh
+++ b/src/celery.sh
@@ -1,4 +1,4 @@
 #!/bin/bash
 nohup celery -A geonode.celery_app:app beat -l DEBUG -f /var/log/celery.log &>/dev/null &
-nohup celery -A geonode.celery_app:app worker --without-gossip --without-mingle -Ofair -B -E --statedb=worker.state -s celerybeat-schedule --loglevel=INFO --concurrency=10 -n worker1@%h -f /var/log/celery.log &>/dev/null &
+nohup celery -A geonode.celery_app:app worker --without-gossip --without-mingle -Ofair -B -E -s django_celery_beat.schedulers:DatabaseScheduler --loglevel=INFO --concurrency=2 -n worker1@%h -f /var/log/celery.log &>/dev/null &
 nohup celery -A geonode.celery_app:app flower --auto_refresh=True --debug=False --broker=${BROKER_URL} --basic_auth=${ADMIN_USERNAME}:${ADMIN_PASSWORD} --address=0.0.0.0 --port=5555 &>/dev/null &

```

### Monitoring Updates accordingly to [7948](https://github.com/GeoNode/geonode/issues/7948)
**issue**: Some `geonode.monitoring` package function have been moved to `geonde.base`

**solution**: From now on, on every setup based on 3.2.x, 3.3.x, 4.0.0 please update your `geonode-projects` as follows.

```diff
diff --git a/src/geonode_master/urls.py b/src/geonode_master/urls.py
index 07e60ad..07b694f 100644
--- a/src/geonode_master/urls.py
+++ b/src/geonode_master/urls.py
@@ -22,7 +22,7 @@ from django.conf.urls import url, include
 from django.views.generic import TemplateView

 from geonode.urls import urlpatterns
-from geonode.monitoring import register_url_event
+from geonode.base import register_url_event

 urlpatterns += [
 ## include your urls here
diff --git a/src/pavement.py b/src/pavement.py
index 85ed417..ea9d805 100644
--- a/src/pavement.py
+++ b/src/pavement.py
@@ -327,7 +327,9 @@ def static(options):
 def setup(options):
     """Get dependencies and prepare a GeoNode development environment."""

-    updategeoip(options)
+    if MONITORING_ENABLED:
+        updategeoip(options)
+
     info(('GeoNode development environment successfully set up.'
           'If you have not set up an administrative account,'
           ' please do so now. Use "paver start" to start up the server.'))
@@ -405,11 +407,12 @@ def updategeoip(options):
     """
     Update geoip db
     """
-    settings = options.get('settings', '')
-    if settings and 'DJANGO_SETTINGS_MODULE' not in settings:
-        settings = 'DJANGO_SETTINGS_MODULE=%s' % settings
+    if MONITORING_ENABLED:
+        settings = options.get('settings', '')
+        if settings and 'DJANGO_SETTINGS_MODULE' not in settings:
+            settings = 'DJANGO_SETTINGS_MODULE=%s' % settings

-    sh("%s python -W ignore manage.py updategeoip -o" % settings)
+        sh("%s python -W ignore manage.py updategeoip -o" % settings)


 @task
diff --git a/src/tasks.py b/src/tasks.py
index 831eca8..1750f8d 100644
--- a/src/tasks.py
+++ b/src/tasks.py
@@ -95,7 +95,7 @@ def update(ctx):
         "static_root": os.environ.get('STATIC_ROOT', '/mnt/volumes/statics/static/'),
         "media_root": os.environ.get('MEDIA_ROOT', '/mnt/volumes/statics/uploaded/'),
         "geoip_path": os.environ.get('GEOIP_PATH', '/mnt/volumes/statics/geoip.db'),
-        "monitoring": os.environ.get('MONITORING_ENABLED', True),
+        "monitoring": os.environ.get('MONITORING_ENABLED', False),
         "monitoring_host_name": os.environ.get('MONITORING_HOST_NAME', 'geonode'),
         "monitoring_service_name": os.environ.get('MONITORING_SERVICE_NAME', 'local-geonode'),
         "monitoring_data_ttl": os.environ.get('MONITORING_DATA_TTL', 7),
@@ -186,8 +186,9 @@ def update(ctx):
 def migrations(ctx):
     print("**************************migrations*******************************")
     ctx.run(f"python manage.py migrate --noinput --settings={_localsettings()}", pty=True)
-    ctx.run(f"python manage.py updategeoip --settings={_localsettings()}", pty=True)
     try:
+        if os.environ.get('MONITORING_ENABLED', False):
+            ctx.run(f"python manage.py updategeoip --settings={_localsettings()}", pty=True)
         ctx.run(f"python manage.py rebuild_index --noinput --settings={_localsettings()}", pty=True)
     except Exception:
         pass
@@ -274,8 +275,8 @@ def monitoringfixture(ctx):
 @task
 def updategeoip(ctx):
     print("**************************update geoip*******************************")
-    ctx.run(f"django-admin.py updategeoip \
---settings={_localsettings()}", pty=True)
+    if os.environ.get('MONITORING_ENABLED', False):
+        ctx.run(f"django-admin.py updategeoip --settings={_localsettings()}", pty=True)
 
 
 @task
```

**Comment by marlowp** [comment] 2021-10-01 16:03
Thanks @afabiani. My project has encountered a similar issue to the one highlighted here and we're in the process of upgrading to GeoNode 3.2.1 so hopefully we will not encounter it after the upgrade.

**Comment by afabiani** [comment] 2021-10-04 08:31
@marlowp it is possible the 3.2.1 is still affected by this issue, I can't remember. Better to move to 3.2.x (aka 3.2.2)

**Closed** 2024-02-02 15:38 UTC
