### ISSUE TITLE
Layer thumbnail doesnt always match layer extent.

### ISSUE THREAD

**Issue by jj0hns0n** [GeoNode/geonode#1828] opened 2014-11-24 15:59 UTC
I've now seen several examples of thumbnails that dont match the Minimum extent of the associated layer.

**Comment by jj0hns0n** [comment] 2015-01-13 16:46
We should have an integration test for this

**Comment by capooti** [comment] 2015-01-17 10:30
is this a duplicate of #1462?

**Comment by jj0hns0n** [comment] 2015-01-17 18:10
@capooti I think they are different but related. We should be able to close these together with a good fix during the sprint.

**Comment by jj0hns0n** [comment] 2015-02-03 11:31
@simod can we now close this?

**Closed** 2018-04-11 08:12 UTC
Labels: layers
