### ISSUE TITLE
preserving XML file

### ISSUE THREAD

**Issue by d3netxer** [GeoNode/geonode#2474] opened 2016-04-25 18:08 UTC
I have uploaded an XML file with the shapefile I uploaded to GeoNode, but when I download the shapefile the XML file is not there anymore. The XML file should be preserved.

**Comment by pjdufour** [comment] 2016-04-26 11:46
GeoNode's geoserver doesn't package the metadata (as *.xml) with a zipfile download (or any GeoServer by default).  This is a feature request and not a bug.  Will require some geoserver integration work, using WPS or WFS.

See https://github.com/GeoNode/geonode/issues/1240 for more info.

For bulk downloads, use scripts to download the zipfile, download the metadata, and then add the metadata to the zip.

Closing, b/c duplicate.

**Closed by pjdufour** 2016-04-26 11:46 UTC
Labels: feature-request

**Comment by pjdufour** [comment] 2016-04-26 11:47
GeoNode's geoserver doesn't package the metadata (as *.xml) with a zipfile download (or any GeoServer by default). This is a feature request and not a bug. Will require some geoserver integration work, using WPS or WFS.

See #1240 for more info.

Closing, b/c duplicate.

**Comment by vdeparday** [comment] 2016-04-26 16:50
@d3netxer you can download the .xml separately from the download metadata button but yes it would be better to have them packaged together as described in #1240
