### ISSUE TITLE
sync_geonode_layers, sync_geofence set geofence rule ROLE_ANONYMOUS

### ISSUE THREAD

**Issue by t-book** [GeoNode/geonode#4186] opened 2019-01-25 18:28 UTC
Hi,

this might be a matter of misconfiguration. 

`$ paver setup_data`

**Initial standard permissions/rules are:**
![gui](https://user-images.githubusercontent.com/20478652/51764428-7b48c400-20d5-11e9-81da-858acb3409c7.png)

* Non loged-in users can correctly view the resource. 
* Same rules are created when changing the permissions from layer details view.

**However,** 
when deleting the rules and setting them again using `sync_geonode_layers` or `sync_geofence` like:
`python manage.py sync_geonode_layers --filter="san_andres_y_providencia_natural"`
ROLE_ANONYMOUS is set instead of `*`. Which forbids viewing the layer for non logged in users.

![syc_geonode_layers](https://user-images.githubusercontent.com/20478652/51765224-813fa480-20d7-11e9-93e2-dabd7be4dd14.png)

What am I´m missing?

**Comment by afabiani** [comment] 2019-01-31 08:43
@t-book I will double check, thanks.

**Comment by afabiani** [comment] 2019-04-01 09:01
@t-book this should be fixed now on master.
The commands now put rules for both ROLE_ANONYMOUS and '*' making the layer visible again to non logged-in users/user recognized ad "ANONYMOUS".

Also this PR https://github.com/GeoNode/geonode/pull/4326

Improves the commands and removes the "sync_geofence" which seems to be a sort of duplicate of the other one.

**Comment by afabiani** [comment] 2019-04-08 14:47
Tests here seem to be good. I'm closing this for now.
If this is happening again (hopefully not) we will reopen a specific issue.

**Closed by afabiani** 2019-04-08 14:47 UTC
Labels: major

**Comment by t-book** [comment] 2019-04-08 15:00
Thanks @afabiani, can confirm not happening here anymore as well.
