### ISSUE TITLE
db healthcheck fails with 'FATAL:  role "root" does not exist'

### ISSUE THREAD

**Issue by gannebamm** [GeoNode/geonode#9839] opened 2022-08-09 16:29 UTC
## Expected Behavior
The db healthcheck (https://github.com/GeoNode/geonode/blob/master/docker-compose.yml#L138) will return meaningful insights.

## Actual Behavior
The healthcheck fails with `FATAL:  role "root" does not exist`

## Steps to Reproduce the Problem

  1. clone geonode at 4.x
  2. docker-compose build
  3. docker-compose up
  4. take a look at the db log

## Specifications

  - GeoNode version: 4.x ()
  - Installation method (manual, GeoNode Docker, SPCGeoNode Docker): GeoNode Docker
  - Platform: Ubuntu
  - Additional details:

`test: "pg_isready -U postgres -d geonode"` could do the trick since it will use the postgres user and pings the database 'geonode'.

**Comment by Inogeo** [comment] 2022-08-10 14:24
I am not sure it is a proper fix, but did you try removing all docker volumes before installing geonode ? It looks to be working on my side. I have ```test: "pg_isready -d geonode" ``` working.

**Comment by t-book** [comment] 2022-08-12 14:14
@gannebamm I can confirm this with geonode project. 
@Inogeo removing volumes is no option. Think of all the people who need to migrate.

**Comment by t-book** [comment] 2022-08-12 14:57
@gannebamm this fixes the healthcheck in my tests:

```
    healthcheck:
      test: "pg_isready -d postgres -U postgres"
```
      
but still the startpage is only showing a spinning wheel ...

**Comment by t-book** [comment] 2022-08-12 15:01
@gannebamm after you've fixed the health check, please try the following:

1. log in with your admin account
2. Visit the splash page that should load now.
3. upload test data
4. log out
5. visit the splash page as anonymous

It should load now. Can you confirm? (If so, this behavior is really strange and should be fixed)

**Comment by gannebamm** [comment] 2022-08-12 15:34
> @gannebamm this fixes the healthcheck in my tests:
> 
> ```
>     healthcheck:
>       test: "pg_isready -d postgres -U postgres"
> ```
> 
> but still the startpage is only showing a spinning wheel ...

Which will do the trick but in production we should check the geonode dbs, shouldn't we?

The start page issue is not related with this issue. @mattiagiupponi has already provided a fix in his pr #9841

**Comment by t-book** [comment] 2022-08-12 15:41
Well I would say the reason for the healthcheck is to see if the database is up not if the geonode database exists, as postgres always has the db postgres it is IMHO more generic. But sure if there is a nice way to set the geonode db in question, this would work as well
 
 https://github.com/GeoNode/geonode/pull/9841 cool!

**Comment by gannebamm** [comment] 2022-08-15 14:30
@t-book I used your more generic healthcheck: #9855

**Closed** 2022-08-24 08:53 UTC
Labels: docker, 4.0.x
