### ISSUE TITLE
Issue in GeoServer when exporting a layer with a spatial filter

### ISSUE THREAD

**Issue by Stella-Nthenya** [GeoNode/geonode#8734] opened 2022-02-03 12:07 UTC
## Expected Behavior
A user should be able to filter and export data

## Actual Behavior
Can not filter and export data with Area of interest 

## Steps to Reproduce the Problem

  1. View a layer and click on filter layer
  2. Add an area of interest and save
  3. Click on export data
  4. Select a format and enable download filtered dataset
  5. Click on export

## Specifications

  - GeoNode version: 3.3x
  - Installation method (manual, GeoNode Docker, SPCGeoNode Docker):
  - Platform: 
  - Additional details:

**Comment by Stella-Nthenya** [comment] 2022-02-03 12:08
@giohappy @ElenaGallo I have raised a ticket for this issue

**Comment by giohappy** [comment] 2022-02-03 15:03
I could reproduce the error.

REQUEST:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<wps:Execute xmlns:wps="http://www.opengis.net/wps/1.0.0" xmlns="http://www.opengis.net/wps/1.0.0" xmlns:dwn="http://geoserver.org/wps/download" xmlns:gml="http://www.opengis.net/gml" xmlns:ogc="http://www.opengis.net/ogc" xmlns:ows="http://www.opengis.net/ows/1.1" xmlns:wcs="http://www.opengis.net/wcs/1.1.1" xmlns:wfs="http://www.opengis.net/wfs" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" version="1.0.0" service="WPS" xsi:schemaLocation="http://www.opengis.net/wps/1.0.0 http://schemas.opengis.net/wps/1.0.0/wpsAll.xsd">
   <ows:Identifier>gs:Download</ows:Identifier>
   <wps:DataInputs>
      <wps:Input>
         <ows:Identifier>layerName</ows:Identifier>
         <wps:Data>
            <wps:LiteralData>geonode:states1</wps:LiteralData>
         </wps:Data>
      </wps:Input>
      <wps:Input>
         <ows:Identifier>outputFormat</ows:Identifier>
         <wps:Data>
            <wps:LiteralData>application/zip</wps:LiteralData>
         </wps:Data>
      </wps:Input>
      <wps:Input>
         <ows:Identifier>filter</ows:Identifier>
         <wps:Data>
            <wps:ComplexData mimeType="text/xml; subtype=filter/1.1"><![CDATA[<ogc:Filter xmlns:ogc="http://www.opengis.net/ogc" xmlns:gml="http://www.opengis.net/gml"><ogc:And><ogc:Intersects><ogc:PropertyName>the_geom</ogc:PropertyName><gml:Polygon srsName="EPSG:3857"><gml:outerBoundaryIs><gml:LinearRing><gml:coordinates>-11774971.33327483,5530371.870489072 -11774971.33327483,4439462.602803037 -9964942.503481857,4439462.602803037 -9964942.503481857,5530371.870489072 -11774971.33327483,5530371.870489072</gml:coordinates></gml:LinearRing></gml:outerBoundaryIs></gml:Polygon></ogc:Intersects></ogc:And></ogc:Filter>]]></wps:ComplexData>
         </wps:Data>
      </wps:Input>
      <wps:Input>
         <ows:Identifier>cropToROI</ows:Identifier>
         <wps:Data>
            <wps:LiteralData>false</wps:LiteralData>
         </wps:Data>
      </wps:Input>
   </wps:DataInputs>
   <wps:ResponseForm>
      <wps:ResponseDocument storeExecuteResponse="true" status="true">
         <wps:Output mimeType="application/zip" asReference="true">
            <ows:Identifier>result</ows:Identifier>
         </wps:Output>
      </wps:ResponseDocument>
   </wps:ResponseForm>
</wps:Execute>
```

EXCEPTION:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<wps:ExecuteResponse xmlns:wps="http://www.opengis.net/wps/1.0.0" xmlns:ows="http://www.opengis.net/ows/1.1" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:xs="http://www.w3.org/2001/XMLSchema" xml:lang="en" service="WPS" serviceInstance="https://development.demo.geonode.org/geoserver/ows?" statusLocation="https://development.demo.geonode.org/geoserver/ows?service=WPS&amp;version=1.0.0&amp;request=GetExecutionStatus&amp;executionId=25d3682b-c9e0-4b51-8651-dc04603f0b43" version="1.0.0">
   <wps:Process wps:processVersion="1.0.0">
      <ows:Identifier>gs:Download</ows:Identifier>
      <ows:Title>Enterprise Download Process</ows:Title>
      <ows:Abstract>Downloads Layer Stream and provides a ZIP.</ows:Abstract>
   </wps:Process>
   <wps:Status creationTime="2022-02-03T14:45:43.576Z">
      <wps:ProcessFailed>
         <ows:ExceptionReport version="1.1.0">
            <ows:Exception exceptionCode="NoApplicableCode">
               <ows:ExceptionText>Process failed during execution
java.lang.IllegalStateException: Got an empty feature collection.
Got an empty feature collection.</ows:ExceptionText>
            </ows:Exception>
         </ows:ExceptionReport>
      </wps:ProcessFailed>
   </wps:Status>
</wps:ExecuteResponse>
```

Geoserver log:
```
2022-02-03 14:45:09,962 ERROR [wps.executor] - Process execution failed
org.geotools.process.ProcessException: java.lang.IllegalStateException: Got an empty feature collection.
	at org.geoserver.wps.gs.download.DownloadProcess.execute(DownloadProcess.java:501)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.geotools.process.factory.AnnotationDrivenProcessFactory$InvokeMethodProcess.execute(AnnotationDrivenProcessFactory.java:622)
	at org.geoserver.wps.executor.ProcessStartupFilter$ProcessStartupWrapper.execute(ProcessStartupFilter.java:50)
	at org.geoserver.wps.executor.DefaultProcessManager$ProcessCallable.call(DefaultProcessManager.java:223)
	at org.geoserver.wps.executor.DefaultProcessManager$ProcessCallable.call(DefaultProcessManager.java:191)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IllegalStateException: Got an empty feature collection.
	at org.geoserver.wps.gs.download.DownloadUtilities.checkIsEmptyFeatureCollection(DownloadUtilities.java:157)
	at org.geoserver.wps.gs.download.VectorDownload.execute(VectorDownload.java:163)
	at org.geoserver.wps.gs.download.DownloadProcess.execute(DownloadProcess.java:367)
	... 12 more
```

Here below some filtered downloads requests that work:

Spatial filter expressed as ROI input parameter:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<wps:Execute xmlns:wps="http://www.opengis.net/wps/1.0.0" xmlns="http://www.opengis.net/wps/1.0.0" xmlns:dwn="http://geoserver.org/wps/download" xmlns:gml="http://www.opengis.net/gml" xmlns:ogc="http://www.opengis.net/ogc" xmlns:ows="http://www.opengis.net/ows/1.1" xmlns:wcs="http://www.opengis.net/wcs/1.1.1" xmlns:wfs="http://www.opengis.net/wfs" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" version="1.0.0" service="WPS" xsi:schemaLocation="http://www.opengis.net/wps/1.0.0 http://schemas.opengis.net/wps/1.0.0/wpsAll.xsd">
   <ows:Identifier>gs:Download</ows:Identifier>
   <wps:DataInputs>
      <wps:Input>
         <ows:Identifier>layerName</ows:Identifier>
         <wps:Data>
            <wps:LiteralData>geonode:tres</wps:LiteralData>
         </wps:Data>
      </wps:Input>
      <wps:Input>
         <ows:Identifier>outputFormat</ows:Identifier>
         <wps:Data>
            <wps:LiteralData>application/zip</wps:LiteralData>
         </wps:Data>
      </wps:Input>
      <wps:Input>
         <ows:Identifier>ROI</ows:Identifier>
         <wps:Data>
            <wps:ComplexData mimeType="application/json"><![CDATA[{"type":"Polygon","coordinates":[[[-8248796.28589222,515166.809978058],[-8248796.28589222,519299.1868197253],[-8242920.189342797,519299.1868197253],[-8242920.189342797,515166.809978058],[-8248796.28589222,515166.809978058]]]}]]></wps:ComplexData>
         </wps:Data>
      </wps:Input>
      <wps:Input>
         <ows:Identifier>RoiCRS</ows:Identifier>
         <wps:Data>
            <wps:LiteralData>EPSG:3857</wps:LiteralData>
         </wps:Data>
      </wps:Input>
      <wps:Input>
         <ows:Identifier>cropToROI</ows:Identifier>
         <wps:Data>
            <wps:LiteralData>true</wps:LiteralData>
         </wps:Data>
      </wps:Input>
   </wps:DataInputs>
   <wps:ResponseForm>
      <wps:ResponseDocument storeExecuteResponse="true" status="true">
         <wps:Output mimeType="application/zip" asReference="true">
            <ows:Identifier>result</ows:Identifier>
         </wps:Output>
      </wps:ResponseDocument>
   </wps:ResponseForm>
</wps:Execute>
```

Attribute filter:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<wps:Execute xmlns:wps="http://www.opengis.net/wps/1.0.0" xmlns="http://www.opengis.net/wps/1.0.0" xmlns:dwn="http://geoserver.org/wps/download" xmlns:gml="http://www.opengis.net/gml" xmlns:ogc="http://www.opengis.net/ogc" xmlns:ows="http://www.opengis.net/ows/1.1" xmlns:wcs="http://www.opengis.net/wcs/1.1.1" xmlns:wfs="http://www.opengis.net/wfs" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" version="1.0.0" service="WPS" xsi:schemaLocation="http://www.opengis.net/wps/1.0.0 http://schemas.opengis.net/wps/1.0.0/wpsAll.xsd">
   <ows:Identifier>gs:Download</ows:Identifier>
   <wps:DataInputs>
      <wps:Input>
         <ows:Identifier>layerName</ows:Identifier>
         <wps:Data>
            <wps:LiteralData>geonode:tres</wps:LiteralData>
         </wps:Data>
      </wps:Input>
      <wps:Input>
         <ows:Identifier>outputFormat</ows:Identifier>
         <wps:Data>
            <wps:LiteralData>application/zip</wps:LiteralData>
         </wps:Data>
      </wps:Input>
      <wps:Input>
         <ows:Identifier>filter</ows:Identifier>
         <wps:Data>
            <wps:ComplexData mimeType="text/xml; subtype=filter/1.1"><![CDATA[<ogc:Filter xmlns:ogc="http://www.opengis.net/ogc" xmlns:gml="http://www.opengis.net/gml"><ogc:And><ogc:And><ogc:And><ogc:PropertyIsGreaterThan><ogc:PropertyName>value</ogc:PropertyName><ogc:Literal>1000</ogc:Literal></ogc:PropertyIsGreaterThan></ogc:And></ogc:And></ogc:And></ogc:Filter>]]></wps:ComplexData>
         </wps:Data>
      </wps:Input>
      <wps:Input>
         <ows:Identifier>cropToROI</ows:Identifier>
         <wps:Data>
            <wps:LiteralData>false</wps:LiteralData>
         </wps:Data>
      </wps:Input>
   </wps:DataInputs>
   <wps:ResponseForm>
      <wps:ResponseDocument storeExecuteResponse="true" status="true">
         <wps:Output mimeType="application/zip" asReference="true">
            <ows:Identifier>result</ows:Identifier>
         </wps:Output>
      </wps:ResponseDocument>
   </wps:ResponseForm>
</wps:Execute>
```

Apparently the WPS export fails when a spatial filter is set.

**Comment by simboss** [comment] 2022-02-03 15:15
linked to [this](https://github.com/geosolutions-it/geoserver/issues/324).

**Comment by afabiani** [comment] 2022-02-03 16:35
duplicate of https://github.com/GeoNode/geonode/issues/8460

**Comment by giohappy** [comment] 2022-02-03 17:19
@afabiani we can close this, but I would clarify that the issue is only with spatial filters. Attributes filters work fine.

**Comment by Stella-Nthenya** [comment] 2022-02-03 17:33
This issue is not in [master](master.demo.geonode.org)

**Comment by giohappy** [comment] 2022-02-04 17:24
I've updated the issue opened by @afabiani, restricintg the case to spatial filters.
@Stella-Nthenya I don't know why you reported that it's working on master. From the tests of mine and @allyoucanmap it's failing also on master. Anyway, we will double check when the "Filter" tool will be added to the dataset editors (see https://github.com/GeoNode/geonode-mapstore-client/issues/791)

**Closed by giohappy** 2022-02-04 17:24 UTC
Labels: in test, investigation, geoserver, 3.3.x
