### ISSUE TITLE
Misleading values in Analytics view

### ISSUE THREAD

**Issue by simboss** [GeoNode/geonode#5618] opened 2020-02-06 11:53 UTC
## Expected Behavior
On master.demo we have currently slightly more than 1.5k layers but the **Current Number of Resources** widget reports 2k.

## Actual Behavior
I would expect the widget to show something like 1.5k otherwise the granularity is too coarse.

## Steps to Reproduce the Problem

  1. Login as admin on master.demo (yeah, not easy :))
  2. Browse to [this](https://master.demo.geonode.org/monitoring/#/analytics/details/layer/time-range/month/date/2020-01-01T00:00:00.000Z/) page
  3. Check the **Layers** widget value and show the tooltip with the correct value.

## Specifications

  - GeoNode version: 2.10.x
  - Installation method: GeoNode Docker
  - Platform: Ubuntu
  - Additional details: GeoNode Rocks!

**Comment by travislbrundage** [comment] 2020-03-26 17:19
This seems simple enough so I can grab this while I am working on monitoring anyway.

**Comment by travislbrundage** [comment] 2020-03-28 21:53
Just a quick note/update, all I know so far is this line is where the issue is: https://github.com/GeoNode/geonode/blob/master/geonode/monitoring/frontend/src/components/Counter.jsx#L43

Do not yet know why it is rounding.

**Comment by t-book** [comment] 2020-03-29 07:14
@travislbrundage here is my guess:

The current amount is correctly fetched here:
https://github.com/GeoNode/geonode/blob/031781ecc674c94f6d95b8f737d42ed5b27bf7c8/geonode/monitoring/frontend/src/api/index.js#L153-L165

imported here:
https://github.com/GeoNode/geonode/blob/031781ecc674c94f6d95b8f737d42ed5b27bf7c8/geonode/monitoring/frontend/src/pages/AnalyticsOverview.jsx#L38


and used here:
https://github.com/GeoNode/geonode/blob/031781ecc674c94f6d95b8f737d42ed5b27bf7c8/geonode/monitoring/frontend/src/pages/AnalyticsOverview.jsx#L93-L102

I am unsure but my guess is `<FormattedMessage id="count" defaultMessage="Count"/>` could round the value?

> This library provides React components and an API to format dates, numbers, and strings, including pluralization and handling translations.
https://github.com/formatjs/react-intl

**Comment by travislbrundage** [comment] 2020-03-30 20:07
That is really helpful, I actually did not notice that `FormattedMessage` component, I think you are probably right. I confirmed the other things you mentioned as well, the right value is coming through the functions, not rounded, but something in the UI is just rounding it up - it is probably that component.

**Comment by gannebamm** [comment] 2020-04-02 19:21
@giohappy Should @travislbrundage keep this on hold, too? Do you work on this already?

**Comment by giohappy** [comment] 2020-04-03 08:23
@travislbrundage please go ahead with the fixes. I suggest to let @allyoucanmap do a review of your PR

**Comment by allyoucanmap** [comment] 2020-04-03 09:05
@t-book , @travislbrundage I did some test and it seems the library

**Comment by allyoucanmap** [comment] 2020-04-03 09:18
Sorry I accidentally close the issue.

@t-book @travislbrundage
It seems also the [numeral](https://github.com/adamwdraper/Numeral-js) library don't format correctly the value with 'Oa'. https://github.com/adamwdraper/Numeral-js/issues/283
I did a quick test with [numbro](https://github.com/BenjaminVanRyseghem/numbro) and seems to have better format options.
```js
numbro(count).format({
    average: true,
    mantissa: 1,
})

```
numeral is used in these components:
https://github.com/GeoNode/geonode/blob/master/geonode/monitoring/frontend/src/components/Counter.jsx#L29
https://github.com/GeoNode/geonode/blob/master/geonode/monitoring/frontend/src/components/Chart.jsx#L42

**Comment by t-book** [comment] 2020-04-03 09:30
@allyoucanmap so you would suggest to just replace the lib? If so @travislbrundage do you have capacities to take care of?

**Comment by allyoucanmap** [comment] 2020-04-03 10:05
> @allyoucanmap so you would suggest to just replace the lib?
@t-book yes, I would suggest to update the library

I tried with these changes and it seems to work as expected even if the precision of value depends on the mantissa property.
https://github.com/GeoNode/geonode/compare/master...allyoucanmap:misleading-values-analytics
in the commit there are also updates for jest test library and webpack remote connections I was testing locally

**Comment by giohappy** [comment] 2020-04-03 10:56
@t-book if you can test the branch from @allyoucanmap it would be great, than we can ask him to create a PR

**Comment by t-book** [comment] 2020-04-04 07:49
@giohappy 

Quick and dirty some test data. (1533 to reach the 2k formating)
```
for i in range(1533):
  l = Layer()
  l.name = str(i)
  l.save()
```

<img width="328" alt="Bildschirmfoto 2020-04-04 um 09 46 13" src="https://user-images.githubusercontent.com/20478652/78421599-3addc200-7659-11ea-8cef-0ef18e46fb7f.png">

---

After creating a build from branch of @allyoucanmap 

<img width="320" alt="Bildschirmfoto 2020-04-04 um 09 47 49" src="https://user-images.githubusercontent.com/20478652/78421625-61036200-7659-11ea-94e5-e34583359d72.png">

I think this does it!

**Closed** 2020-06-10 08:54 UTC
Labels: minor, wontfix
