### ISSUE TITLE
Error when saving a new map

### ISSUE THREAD

**Issue by italogsfernandes** [GeoNode/geonode#8446] opened 2021-11-30 12:41 UTC
## Expected Behavior
* When saving a new map, the map should be saved.

## Actual Behavior
* Network error

![image_2021_11_30T10_50_14_497Z](https://user-images.githubusercontent.com/12943132/144049181-914229db-2047-4dab-8717-908df45cd842.png)

## Steps to Reproduce the Problem

  1. Add a layer.
  2. Try to create a map with this layer.
  3. Wait for error.

## Specifications

  - GeoNode version: 4.0.0
  - Installation method (manual, GeoNode Docker, SPCGeoNode Docker): Docker
  - Platform: https://master.demo.geonode.org/#/
  - Additional details:

**Comment by giohappy** [comment] 2021-11-30 17:00
@afabiani can you please investigate this issue on master demo? It happens "randomly" and I wasn't able to see any relevant log.
I suspect that something goes wrong inside celery, and final effect is a truncated connection

**Comment by afabiani** [comment] 2021-12-21 15:10
@giohappy after several tests, also locally by forcing a timeout through a fake long request, I can confirm that this is an issue with the client truncating long requests exactly after 10 seconds.

**Comment by allyoucanmap** [comment] 2021-12-21 15:50
@giohappy @afabiani yes, the client introduced it here
https://github.com/GeoNode/geonode-mapstore-client/blob/master/geonode_mapstore_client/client/js/api/geonode/v2/index.js#L508
going to remove the timeout in the request and closing this issue

**Closed by allyoucanmap** 2021-12-21 15:50 UTC
Labels: minor, master

**Comment by tjnu1830080255** [comment] 2023-07-06 02:54
> @giohappy @afabiani是的，客户端在这里介绍了它 https://github.com/GeoNode/geonode-mapstore-client/blob/master/geonode_mapstore_client/client/js/api/geonode/v2/index.js#L508 将超时删除请求并关闭此问题

Very sorry for disturbing you. I encountered the problem of "Network error" when saving the map. I have used the 4.1.0 version of geonode. The solution you described has been modified, but this problem still exists. Do you have any solution?
According to my test, it's not because the file is too large.
This is the issue I raised.
https://github.com/GeoNode/geonode/issues/11221
