### ISSUE TITLE
geonode generating invalid SQL

### ISSUE THREAD

**Issue by gubuntu** [GeoNode/geonode#2245] opened 2015-07-28 10:47 UTC
with 2.4b25 on 14.04

postgresql log during layer upload:

2015-07-28 11:15:38 SAST ERROR:  operator does not exist: json = json at character 19
2015-07-28 11:15:38 SAST HINT:  No operator matches the given name and argument type(s). You might need to add explicit type casts.
2015-07-28 11:15:38 SAST STATEMENT:  SELECT '{}'::json = '{}'::json;

**Comment by jj0hns0n** [comment] 2015-11-18 19:48
@gubuntu how can we replicate this? Have you tested against the latest RC?

**Comment by jj0hns0n** [comment] 2016-08-22 12:26
As far as we can tell, GeoNode does not issue these SAST statements and we are unable to reproduce. Closing. @gubuntu let us know if you are able to provide a means to reproduce.

**Closed by jj0hns0n** 2016-08-22 12:26 UTC
Labels: bug, upload
