### ISSUE TITLE
Wrong link to geoserver admin gui

### ISSUE THREAD

**Issue by ablaye** [GeoNode/geonode#5455] opened 2019-12-27 15:01 UTC
## Expected Behavior
I expected https://www.example.org/geoserver/

## Actual Behavior
The actual behavior is https://www.example.orggeoserver
## Steps to Reproduce the Problem

  1. I configure my geonode to work on ip and www.example.org
  2. The domaine name is defined on a proxy server by using a proxyPass
  3. the link to my geonode works on www.example.org but my geoserver is not working. when I click on 'Admin' -> 'Geoserver', I got https://www.example.orggeoserver/

## Specifications

  - GeoNode version: 2.10
  - Installation method (manual, GeoNode Docker, SPCGeoNode Docker): manual
  - Platform: ubuntu 18.04
  - Additional details:

**Comment by t-book** [comment] 2019-12-27 17:32
I cannot reproduce this . My guess is something is not correctly setup with your settings.py or proxy. for settings.py have a look here https://github.com/GeoNode/geonode/blob/master/geonode/settings.py#L867 where the link is build.

**Comment by t-book** [comment] 2020-01-07 09:23
@ablaye I'm closing here. In case this problem longer exists, please ask for help at osgeo user or dev list.

**Closed by t-book** 2020-01-07 09:23 UTC
Labels: question
