### ISSUE TITLE
Rating average available only in English

### ISSUE THREAD

**Issue by etj** [GeoNode/geonode#8452] opened 2021-12-01 14:26 UTC
## Expected Behavior

When changing language, ratings average should stay the same.

## Actual Behavior

Ratings average in any other language than English is always 0.
Example from a layer in 2 different languages:
- Italian:
  ![image](https://user-images.githubusercontent.com/717359/144251236-ac713e21-c5c4-4cbd-bd64-9180684f2cac.png)
- English:
  ![image](https://user-images.githubusercontent.com/717359/144251411-19bc01fa-0e50-42fa-9287-b9021e4225f9.png)

## Steps to Reproduce the Problem

  1. Vote a layer
  2. See the average
  3. Change language (to English, if it not was already)
  4. See the average
  
## Specifications

  - GeoNode version: 3.2, 3.3, (dunnno how to replicate on master)

**Comment by giohappy** [comment] 2021-12-09 09:35
duplicate of #8454

**Closed by giohappy** 2021-12-09 09:35 UTC
