### ISSUE TITLE
from celery import Celery, there is no Celery.py

### ISSUE THREAD

**Issue by hyj521** [GeoNode/geonode#3536] opened 2017-12-25 09:26 UTC
Hi 
    in the celery_app.py there is "from celery import Celery", but there is no Celery.py or other Celery.I installed GeoNode-2.6.x . I count't creat a table use "python manage.py makemigrations " too.
![default](https://user-images.githubusercontent.com/33618918/34337163-389c4e9e-e998-11e7-95c1-303171db692e.png)
![default](https://user-images.githubusercontent.com/33618918/34337185-62a808b8-e998-11e7-992d-04da016f6047.png)

**Comment by francbartoli** [comment] 2017-12-25 12:52
Closing since it is a duplicate of #3531

**Closed by francbartoli** 2017-12-25 12:52 UTC
