### ISSUE TITLE
AttributeError at /gs/geonode:[layer]/style/manage => 'NoneType' object has no attribute 'find'

### ISSUE THREAD

**Issue by m431m** [GeoNode/geonode#2265] opened 2015-09-08 09:24 UTC
Hi! I found an error (not really a bug):

```
AttributeError at /gs/geonode:[layer]/style/manage

'NoneType' object has no attribute 'find'

Request Method:   GET
Request URL:  http://adl.webmapping.fr/gs/geonode:[layer]/style/manage
Django Version:   1.6.10
Exception Type:   AttributeError
Exception Value:  

'NoneType' object has no attribute 'find'

Exception Location:   /usr/local/lib/python2.7/dist-packages/geoserver/style.py in sld_title, line 49
Python Executable:  /usr/bin/python
Python Version:   2.7.9
Python Path:  ...
--
    /usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py in get_response
                            response = wrapped_callback(request, *callback_args, **callback_kwargs)

    /usr/local/lib/python2.7/dist-packages/django/contrib/auth/decorators.py in _wrapped_view
                        return view_func(request, *args, **kwargs)

    /home/neogeo/geonode/geonode/geoserver/views.py in layer_style_manage
                        gs_styles.append((style.name, style.sld_title))

    /usr/local/lib/python2.7/dist-packages/geoserver/style.py in sld_title
                title_node = user_style.find("{http://www.opengis.net/sld}Title")
```

So, error is done by : **title_node = user_style.find("{http://www.opengis.net/sld}Title")**.
It is quite normal, and I am wrong, because I'd written the SLD by hand, without respecting strictly the SLD standard (without namespace). But is it really necessary to create document in strict compliance with the standard ? Yes ? Oh no...

**Comment by simod** [comment] 2015-09-08 09:29
@m431m please discuss that on the mailing lists before opening a ticket. I'm going to close this as it doesn't appear to be a bug.

**Comment by m431m** [comment] 2015-09-08 09:33
I think it is a bug. SLD is valid for GeoServer but not for GeoNode.
Maybe, Python exception should be treated.

**Comment by simod** [comment] 2015-09-08 09:42
Tested removing a title from a style and the style disappears from the styles lists in geonode, the issue seems to come from gsconfig, https://github.com/boundlessgeo/gsconfig/blob/master/src/geoserver/style.py#L63.

We can keep this open here and fix then in gsconfig.

Thanks for reporting @m431m!

**Comment by afabiani** [comment] 2015-09-22 09:07
Fix ready

https://github.com/boundlessgeo/gsconfig/pull/133

==
GeoServer Professional Services from the experts! Visit
http://goo.gl/NWWaa2 for more information.
==

Ing. Alessio Fabiani
@alfa7691
Founder/Technical Lead

GeoSolutions S.A.S.
Via Poggio alle Viti 1187
55054  Massarosa (LU)
Italy
phone: +39 0584 962313
fax:     +39 0584 1660272
mob:   +39  331 6233686

http://www.geo-solutions.it
http://twitter.com/geosolutions_it

-------------------------------------------------------

*AVVERTENZE AI SENSI DEL D.Lgs. 196/2003*

Le informazioni contenute in questo messaggio di posta elettronica e/o
nel/i file/s allegato/i sono da considerarsi strettamente riservate. Il
loro utilizzo è consentito esclusivamente al destinatario del messaggio,
per le finalità indicate nel messaggio stesso. Qualora riceviate questo
messaggio senza esserne il destinatario, Vi preghiamo cortesemente di
darcene notizia via e-mail e di procedere alla distruzione del messaggio
stesso, cancellandolo dal Vostro sistema. Conservare il messaggio stesso,
divulgarlo anche in parte, distribuirlo ad altri soggetti, copiarlo, od
utilizzarlo per finalità diverse, costituisce comportamento contrario ai
principi dettati dal D.Lgs. 196/2003.



The information in this message and/or attachments, is intended solely for
the attention and use of the named addressee(s) and may be confidential or
proprietary in nature or covered by the provisions of privacy act
(Legislative Decree June, 30 2003, no.196 - Italy's New Data Protection
Code).Any use not in accord with its purpose, any disclosure, reproduction,
copying, distribution, or either dissemination, either whole or partial, is
strictly forbidden except previous formal approval of the named
addressee(s). If you are not the intended recipient, please contact
immediately the sender by telephone, fax or e-mail and delete the
information in this message that has been received in error. The sender
does not give any warranty or accept liability as the content, accuracy or
completeness of sent messages and accepts no responsibility  for changes
made after they were sent or for other risks which arise as a result of
e-mail transmission, viruses, etc.

**Comment by jj0hns0n** [comment] 2015-11-18 19:47
@m431m we are issuing a new RC3 that will incorporate these changes in gsconfig. Can you test in the next days and close if fixed.

**Closed** 2016-08-22 12:24 UTC
Labels: bug, geoserver-integration
