### ISSUE TITLE
Creating a new style fails with 405

### ISSUE THREAD

**Issue by capooti** [GeoNode/geonode#3861] opened 2018-07-24 20:22 UTC
observed today in latest 2.7.x:
when creating a new style, the style is correctly created in GeoServer but not associated to the layer. I see a 405 at some point: "PUT /gs/rest/styles?raw=true HTTP/1.1" 405 0

**Comment by capooti** [comment] 2018-07-27 19:40
@afabiani any change you can fix this? Otherwise I will take a look

**Comment by afabiani** [comment] 2018-09-04 15:56
@capooti  can you please assign a label to this issue?

**Comment by capooti** [comment] 2018-09-28 18:27
done! sorry, I had an orrible month :D

**Comment by capooti** [comment] 2018-11-21 00:47
This is still happening in the case the user is the owner of the layer but not an administrator.

**Comment by capooti** [comment] 2018-12-05 00:11
Hi @afabiani can you have a look to this?
I tried on vanilla GeoNode master, and it is still failing - with any user including admin. The style seems to be added, but if you reload the page you will see that is not persisted. Thanks!

**Comment by afabiani** [comment] 2018-12-05 08:17
@capooti sure, I'll check it out ASAP. Most probably it's an issue with the GeoServer permissions configuration.

**Comment by capooti** [comment] 2018-12-05 13:57
awesome thanks :)

**Comment by afabiani** [comment] 2019-01-18 11:15
@capooti I tried again but currently I don't know how to reproduce this issue. Can you send me a more detailed use case?

Attaching an animation showing how I tested it on GeoNode master

![geonode-new-style](https://user-images.githubusercontent.com/1278021/51383808-bb7ad600-1b1a-11e9-9d0e-11dca0b3f194.gif)

**Comment by capooti** [comment] 2019-01-18 20:51
I am also on GS master, and I got an error from GS (2.14):

```
org.geowebcache.filter.parameters.ParameterException: Style 'tm_world_borders_0_3_7df2be59' is invalid.
	at org.geoserver.gwc.layer.StyleParameterFilter.apply(StyleParameterFilter.java:97)
	at org.geowebcache.layer.TileLayer.getModifiableParameters(TileLayer.java:563)
	at org.geoserver.gwc.GWC.prepareRequest(GWC.java:893)
	at org.geoserver.gwc.GWC.dispatch(GWC.java:803)
	at org.geoserver.gwc.wms.CachingWebMapService.invoke(CachingWebMapService.java:82)
	at org.geoserver.gwc.wms.CachingWebMapService.invoke(CachingWebMapService.java:52)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.geoserver.ows.util.RequestObjectLogger.invoke(RequestObjectLogger.java:50)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:213)
	at com.sun.proxy.$Proxy124.getMap(Unknown Source)
	at sun.reflect.GeneratedMethodAccessor456.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.geoserver.ows.Dispatcher.execute(Dispatcher.java:877)
	at org.geoserver.ows.Dispatcher.handleRequestInternal(Dispatcher.java:264)
	at org.springframework.web.servlet.mvc.AbstractController.handleRequest(AbstractController.java:174)
	at org.springframework.web.servlet.mvc.SimpleControllerHandlerAdapter.handle(SimpleControllerHandlerAdapter.java:50)
```

Let me download the war again and see if I have the very latest GS version and will be back to you.

**Comment by capooti** [comment] 2019-01-18 20:54
To provide more information, I am also noticing these messages from django:

```
[geoserver_proxy] Updating Style ---> url http://localhost:8080/geoserver/rest/styles?raw=true
Could not recognize Style and Layer name from Request!
Error 404 reading Style Filter Params GeoWebCache at http://localhost:8080/geoserver/gwc/rest/layers/None.xml
Error 500 invalidating GeoWebCache at http://localhost:8080/geoserver/gwc/rest/masstruncate
[geoserver_proxy] Updating Style ---> url http://localhost:8080/geoserver/rest/workspaces/geonode/styles
[geoserver_proxy] Updating Layer ---> url http://localhost:8080/geoserver/rest/layers/tm_world_borders_0_3/styles.json
Could not find any Layer styles.json on DB
[geoserver_proxy] Updating Layer ---> url http://localhost:8080/geoserver/rest/layers/geonode:tm_world_borders_0_3.json
Could not find any Layer geonode:tm_world_borders_0_3.json on DB
[geoserver_proxy] Updating Style ---> url http://localhost:8080/geoserver/rest/workspaces/geonode/styles/tm_world_borders_0_3_7df2be59.xml?raw=true
... Creating Thumbnail for Layer [geonode:tm_world_borders_0_3]
... Creating Thumbnail for Layer [geonode:tm_world_borders_0_3]
[geoserver_proxy] Updating Layer ---> url http://localhost:8080/geoserver/rest/layers/geonode:tm_world_borders_0_3.json
Could not find any Layer geonode:tm_world_borders_0_3.json on DB
```

**Comment by capooti** [comment] 2019-01-18 21:50
Update: using very latest 2.14 now it is possible adding new styles if you are the layer owner. But if you are not the layer owner, it fails with a 405. Can this be fixed?

**Comment by afabiani** [comment] 2019-01-21 09:06
@capooti it is not possible by design (at least on latest GeoServer versions) to modify global styles (global means not belonging to a specific workspace) without being an Administrator.

The options are either:

1. Create only styles under the same layer workspace
2. Proxy the REST requests and acting as an Administrator (a bit dangerous since you are rising up the current user rights)

**Comment by t-book** [comment] 2019-02-12 11:19
I´ve tested with latest master as well but cannot fully agree with @capooti 
In my case even when logged in as admin and adding a new style to a layer which belongs to admin a 405 is thrown.

See testing here: https://vimeo.com/316765057

I double checked rest.properties as suggested by @afabiani  but geoserver logs show below where `Cannot edit global resource` should not happen when having admin permissions?

```
2019-02-12 11:07:10,613 ERROR [geoserver.rest] - Cannot edit global resource , full admin credentials required
org.geoserver.rest.RestException 405 METHOD_NOT_ALLOWED: Cannot edit global resource , full admin credentials required
	at org.geoserver.rest.catalog.AbstractCatalogController.checkFullAdminRequired(AbstractCatalogController.java:125)
	at org.geoserver.rest.catalog.StyleController.stylePost(StyleController.java:119)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:133)
	at 
```

**Comment by giohappy** [comment] 2019-02-12 12:08
yes @t-book, it's going to be fixed soon.

**Comment by t-book** [comment] 2019-02-12 13:36
thanks a lot @giohappy let me know if I can help with testing or something.

**Comment by t-book** [comment] 2019-03-01 09:42
@capooti @giohappy Just tested on master I think we can close this?

**Comment by capooti** [comment] 2019-03-07 16:58
I don't know, just today I am experiencing new issues with two our instances :( (see email in mailing list).
Thought it is very likely they are not connected.

**Comment by t-book** [comment] 2019-03-07 17:28
@capooti eähm :( looks like a regression. I will just give it a try with dev server. Further I´ve a working instance (2 weeks old) where I can diff against

**Comment by afabiani** [comment] 2019-03-07 17:31
@t-book are you experiencing this issue on a recent instance too?

**Comment by t-book** [comment] 2019-03-07 17:34
@afabiani not on an instance installed at 27/03/2019. (master branch). So if it´s a regression it should be some commit after that date. I will do a test with dev server tomorrow and see if it occurs or not.

**Comment by afabiani** [comment] 2019-03-07 17:38
I do not see any meaningful commit after that date into master branch which could affect such functionality!!

**Comment by t-book** [comment] 2019-03-07 17:48
@afabiani Maybe it´s not a geonode commit but with geoserver data directory. Wrong Rest rules? @capooti  In case I cannot reproduce it by tomorrow I could send you my working data-dir folder maybe it could help to diff certain files against your setup.

**Comment by capooti** [comment] 2019-03-07 19:41
@afabiani @capooti I fixed this by updating the rest.properties file in security with latest version - as I have noticed that GeoNode master was not affected, but only with my data directory. Thanks for helping!

**Comment by capooti** [comment] 2019-03-07 19:46
by the way: sticking with the issue in the title, this is still in GeoNode. But at least I can edit styles again. What it is still failing is editing style with a user which is not the owner (getting 405). Let's keep this open.

**Comment by t-book** [comment] 2019-03-07 22:39
@capooti great this worked for you.

**Closed** 2019-07-08 09:56 UTC
Labels: Tested, blocker
