### ISSUE TITLE
Package and release geoserver-geonode with the latest stable

### ISSUE THREAD

**Issue by ingenieroariel** [GeoNode/geonode#2040] opened 2015-02-04 18:04 UTC
2.6 at the time of writing.

**Comment by garnertb** [comment] 2015-02-09 15:09
In case it helps, we have already bumped the GeoSHAPE geoserver build to 2.6.  The GeoSHAPE geoserver build was originally based on the GeoNode geoserver build and the dependencies should be similar.

https://github.com/ROGUE-JCTD/rogue_geonode/blob/master/geoserver_ext/pom.xml

**Comment by auvipy** [comment] 2015-02-23 17:43
django 1.8 is going to be a LTS so syncing geonode django codes with django 1.8/+ should also be on todo list

**Comment by ingenieroariel** [comment] 2015-02-23 19:54
Asif, we are already on another LTS (Ubuntu 14.04 LTS). I suspect Ubuntu
16.04 will ship with Django 1.8 LTS and I think that is the right time to
switch.

**Comment by gamesbook** [comment] 2015-03-24 06:44
2.7 stable now released (http://sourceforge.net/p/geoserver/mailman/message/33630142/)

**Comment by capooti** [comment] 2015-03-24 07:31
I can take care of this later today. So guys, which version to use, LTS 2.5.5 or latest stable 2.7.0?

**Comment by gamesbook** [comment] 2015-03-24 07:37
"My heart says 2.7 but my head says 2.5"
Please see my comments on #2102 about having GeoNode LTS synced with the latest GeoServer LTS, but then ensuring that point releases of GeoNode work with the latest version of GeoServer.

**Comment by ingenieroariel** [comment] 2015-03-25 22:17
For GeoServer, my personal feeling is that we should sync with the latest stable, even if it is not an LTS. The difference between Django and GeoServer here is that Django ships with the platform (Ubuntu) but GeoServer doesn't.

I vote for 2.7.

**Comment by simod** [comment] 2015-03-26 06:55
+1 !!! :-)

Il mercoledì 25 marzo 2015, Ariel Núñez <notifications@github.com> ha
scritto:

> For GeoServer, my personal feeling is that we should sync with the latest
> stable, even if it is not an LTS. The difference between Django and
> GeoServer here is that Django ships with the platform (Ubuntu) but
> GeoServer doesn't.
>
> I vote for 2.7.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/GeoNode/geonode/issues/2040#issuecomment-86235080>.
>


-- 
Simone

**Comment by capooti** [comment] 2015-03-26 09:04
let it be 2.7 then :)

On Thu, Mar 26, 2015 at 7:55 AM, Simone Dalmasso <notifications@github.com>
wrote:

> +1 !!! :-)
>
> Il mercoledì 25 marzo 2015, Ariel Núñez <notifications@github.com> ha
> scritto:
>
>
> > For GeoServer, my personal feeling is that we should sync with the latest
> > stable, even if it is not an LTS. The difference between Django and
> > GeoServer here is that Django ships with the platform (Ubuntu) but
> > GeoServer doesn't.
> >
> > I vote for 2.7.
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/GeoNode/geonode/issues/2040#issuecomment-86235080>.
> >
>
>
> --
> Simone
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/GeoNode/geonode/issues/2040#issuecomment-86363398>.
>



-- 
Paolo Corti
Geospatial software developer
web: http://www.paolocorti.net
twitter: @capooti
skype: capooti

**Comment by gamesbook** [comment] 2015-04-02 10:37
Django 1.8 (LTS) released 1 April 2015.  Give that 1.6 will no longer receive updates, what version of Django will the new release of GeoNode officially support?

**Comment by simod** [comment] 2015-04-02 10:47
I think that it will support the 1.6 which is the one shipped with Ubuntu
14.04.

Il giovedì 2 aprile 2015, Derek Hohls <notifications@github.com> ha scritto:

> Django 1.8 (LTS) released 1 April 2015. Give that 1.6 will no longer
> receive updates, what version of Django will the new release of GeoNode
> officially support?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/GeoNode/geonode/issues/2040#issuecomment-88862364>.
>


-- 
Simone

**Comment by gamesbook** [comment] 2015-04-02 11:37
@simod Given that Django 1.6.11 will be last security update, could that cause problems in future?  What I am saying is: should the project not be more concerned with its core dependency (Django) rather than the OS itself.  I see that the next release of Ubuntu will support 1.7 (http://packages.ubuntu.com/vivid/python-django)..

**Comment by ingenieroariel** [comment] 2015-04-02 12:29
We have gone that route in the past (shipping with latest Django) and it
becomes a problem with packaging.

See for example: https://github.com/GeoNode/geonode/issues/821

That said, the rationale for this was when Django did not have LTS
releases. Is anyone interested in doing a poll to figure this out?

-a

**Comment by auvipy** [comment] 2015-04-07 10:22
while django 1.8 is the latest stable why not use that?

**Comment by matthewhanson** [comment] 2015-05-18 06:09
What is the status of this, was a later version of geoserver-geonode packaged?  The version from build.geonode.org/geoserver/latest/geoserver.war is still 2.5.1.

**Comment by gamesbook** [comment] 2015-05-21 06:27
GeoServer 2.7.1 stable now released (http://sourceforge.net/p/geoserver/mailman/message/34130798/)

**Comment by etj** [comment] 2015-06-16 12:02
Any attempt made so far to upgrade to geoserver 2.7.x?

**Comment by simod** [comment] 2015-06-16 12:04
@etj, don't think that anyone tried that so far. @capooti ?

**Comment by capooti** [comment] 2015-06-16 12:27
nope. I was waiting for the PR to be approved (including latest ones by @etj)
@ingenieroariel @jj0hns0n @ischneider could you eventually review and merge them?
therefore we can proceed I guess

**Comment by ingenieroariel** [comment] 2015-06-26 02:00
Since we have delayed this release so much I think we should just ship with latest Django LTS and latest GeoServer. Votes?

**Comment by garnertb** [comment] 2015-06-26 02:27
+1


On Thu, Jun 25, 2015 at 10:00 PM, Ariel Núñez <notifications@github.com>
wrote:

> Since we have delayed this release so much I think we should just ship
> with latest Django LTS and latest GeoServer. Votes?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/GeoNode/geonode/issues/2040#issuecomment-115462086>.
>



-- 
-Tyler Garner

**Comment by simod** [comment] 2015-06-26 06:32
+1 for geoserver, +1 for django as long as it's not causing troubles.

**Comment by ict4eo** [comment] 2015-06-26 06:44
+1

>>> Ariel Núñez<notifications@github.com> 06/26/15 4:00 AM >>>
Since we have delayed this release so much I think we should just ship
with latest Django LTS and latest GeoServer. Votes?
 —
Reply to this email directly or view it on GitHub.
                 
    
  
--  
This message is subject to the CSIR's copyright terms and conditions,
e-mail legal notice, and implemented Open Document Format (ODF)
standard. 
The full disclaimer details can be found at
http://www.csir.co.za/disclaimer.html.  
This message has been scanned for viruses and dangerous content by
MailScanner,  
and is believed to be clean. 
 
Please consider the environment before printing this email.  



-- 
This message is subject to the CSIR's copyright terms and conditions, e-mail legal notice, and implemented Open Document Format (ODF) standard. 
The full disclaimer details can be found at http://www.csir.co.za/disclaimer.html.

This message has been scanned for viruses and dangerous content by MailScanner, 
and is believed to be clean.

Please consider the environment before printing this email.

**Comment by capooti** [comment] 2015-06-26 08:27
I agree of course for GeoServer.
Regarding Django imho we should have GeoNode working both with the Ubuntu
LTS one (1.6), but also with the latest version (1.8) for security reasons,
and have tests running with both versions.
cheers
p

On Fri, Jun 26, 2015 at 8:44 AM, ICT4EO Research Group <
notifications@github.com> wrote:

> +1
>
> >>> Ariel Núñez<notifications@github.com> 06/26/15 4:00 AM >>>
> Since we have delayed this release so much I think we should just ship
> with latest Django LTS and latest GeoServer. Votes?
> —
> Reply to this email directly or view it on GitHub.
>
>
>
> --
> This message is subject to the CSIR's copyright terms and conditions,
> e-mail legal notice, and implemented Open Document Format (ODF)
> standard.
> The full disclaimer details can be found at
> http://www.csir.co.za/disclaimer.html.
> This message has been scanned for viruses and dangerous content by
> MailScanner,
> and is believed to be clean.
>
> Please consider the environment before printing this email.
>
>
>
> --
> This message is subject to the CSIR's copyright terms and conditions,
> e-mail legal notice, and implemented Open Document Format (ODF) standard.
> The full disclaimer details can be found at
> http://www.csir.co.za/disclaimer.html.
>
> This message has been scanned for viruses and dangerous content by
> MailScanner,
> and is believed to be clean.
>
> Please consider the environment before printing this email.
>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/GeoNode/geonode/issues/2040#issuecomment-115546667>.
>



-- 
Paolo Corti
Geospatial software developer
web: http://www.paolocorti.net
twitter: @capooti
skype: capooti

**Comment by francbartoli** [comment] 2015-07-03 13:58
The attempt to compile against GeoServer 2.7.1 gives me a success with an error related to the creation of the data directory. Anybody who can take a look at this branch [https://github.com/geoavalanche/geoserver-geonode-ext/tree/2.7.x](https://github.com/geoavalanche/geoserver-geonode-ext/tree/2.7.x)?

**Comment by afabiani** [comment] 2015-07-03 15:02
Hi guys,
I can take a look in the next days

**Comment by afabiani** [comment] 2015-07-06 14:59
Dear all, here is the integration of GeoServer 2.7.x with GeoNode master. Have you the chance to test it and report any issue?

https://github.com/geosolutions-it/geoserver-geonode-ext/tree/2.7.x

Regards,
Alessio.

**Comment by jj0hns0n** [comment] 2015-07-09 19:37
@afabiani  The only issue I see is the duplicate guava jars which breaks the homepage but everything else seems to work.

**Comment by afabiani** [comment] 2015-07-10 08:21
The latest pom should avoid the duplicate guava jar issue.

Also, in another pull request which I will prepare in the next few days, I
fixed the known GeoTIFF Importer issue too.

==
GeoServer Professional Services from the experts! Visit
http://goo.gl/NWWaa2 for more information.
==

Ing. Alessio Fabiani
@alfa7691
Founder/Technical Lead

GeoSolutions S.A.S.
Via Poggio alle Viti 1187
55054  Massarosa (LU)
Italy
phone: +39 0584 962313
fax:     +39 0584 1660272
mob:   +39  331 6233686

http://www.geo-solutions.it
http://twitter.com/geosolutions_it

-------------------------------------------------------

*AVVERTENZE AI SENSI DEL D.Lgs. 196/2003*

Le informazioni contenute in questo messaggio di posta elettronica e/o
nel/i file/s allegato/i sono da considerarsi strettamente riservate. Il
loro utilizzo è consentito esclusivamente al destinatario del messaggio,
per le finalità indicate nel messaggio stesso. Qualora riceviate questo
messaggio senza esserne il destinatario, Vi preghiamo cortesemente di
darcene notizia via e-mail e di procedere alla distruzione del messaggio
stesso, cancellandolo dal Vostro sistema. Conservare il messaggio stesso,
divulgarlo anche in parte, distribuirlo ad altri soggetti, copiarlo, od
utilizzarlo per finalità diverse, costituisce comportamento contrario ai
principi dettati dal D.Lgs. 196/2003.



The information in this message and/or attachments, is intended solely for
the attention and use of the named addressee(s) and may be confidential or
proprietary in nature or covered by the provisions of privacy act
(Legislative Decree June, 30 2003, no.196 - Italy's New Data Protection
Code).Any use not in accord with its purpose, any disclosure, reproduction,
copying, distribution, or either dissemination, either whole or partial, is
strictly forbidden except previous formal approval of the named
addressee(s). If you are not the intended recipient, please contact
immediately the sender by telephone, fax or e-mail and delete the
information in this message that has been received in error. The sender
does not give any warranty or accept liability as the content, accuracy or
completeness of sent messages and accepts no responsibility  for changes
made after they were sent or for other risks which arise as a result of
e-mail transmission, viruses, etc.

**Comment by simod** [comment] 2015-10-21 08:35
closing as done

**Closed by simod** 2015-10-21 08:35 UTC
Labels: critical
