### ISSUE TITLE
The button 'Add to map' is not available for admin users (from the layer details page)

### ISSUE THREAD

**Issue by afabiani** [GeoNode/geonode#4660] opened 2019-07-18 12:14 UTC
## Expected Behavior
The button 'Add to map' is available for admin users (from the layer details page)

## Actual Behavior
The button 'Add to map' is not available for admin users (from the layer details page)

## Steps to Reproduce the Problem

  1. Login as admin and Go to the Layer Details page
  2. Make sure there are maps defined into GeoNode
  3. Scroll down looking for the "Add to Map" functionality

## Specifications

  - GeoNode version: 2.10
  - Installation method (manual, GeoNode Docker, SPCGeoNode Docker): any
  - Platform: any
  - Additional details: none

**Comment by t-book** [comment] 2019-08-09 20:43
@afabiani cannot reproduce with 2.10?  

(  Further, nothing looks like doing so in layers detail template https://github.com/GeoNode/geonode/blob/2.10.x/geonode/layers/templates/layers/layer_detail.html#L600  )

**Comment by GeoTob** [comment] 2019-09-23 21:49
I also cannot reproduce this on 2.10 - the button is where I'd expect it to be and works.

![buttons](https://user-images.githubusercontent.com/8564280/65465501-93fdb980-deb0-11e9-8a7b-db1984cfa599.png)

**Comment by t-book** [comment] 2019-10-03 13:29
@afabiani can we close this?

**Closed** 2019-10-03 13:34 UTC
Labels: minor
